// File generated by FlutterFire CLI.
// This is a placeholder. For production, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarypDsma-UFSw0gFw2lv99s1f_bsh4QA',
    appId: '1:490905109908:android:e2b78733448c36fb07fb81',
    messagingSenderId: '490905109908',
    projectId: 'maxbillup',
    authDomain: 'maxbillup.firebaseapp.com',
    storageBucket: 'maxbillup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAarypDsma-UFSw0gFw2lv99s1f_bsh4QA',
    appId: '1:490905109908:android:e2b78733448c36fb07fb81',
    messagingSenderId: '490905109908',
    projectId: 'maxbillup',
    storageBucket: 'maxbillup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAarypDsma-UFSw0gFw2lv99s1f_bsh4QA',
    appId: '1:490905109908:ios:e2b78733448c36fb07fb81',
    messagingSenderId: '490905109908',
    projectId: 'maxbillup',
    storageBucket: 'maxbillup.firebasestorage.app',
    iosBundleId: 'com.example.maxmybill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAarypDsma-UFSw0gFw2lv99s1f_bsh4QA',
    appId: '1:490905109908:ios:e2b78733448c36fb07fb81',
    messagingSenderId: '490905109908',
    projectId: 'maxbillup',
    storageBucket: 'maxbillup.firebasestorage.app',
    iosBundleId: 'com.example.maxmybill',
  );
}
