import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguageCode = 'en'; // Default to English

  String get currentLanguageCode => _currentLanguageCode;

  // Language configurations - International languages first, regional (Hindi/Tamil) at bottom
  final Map<String, Map<String, String>> _languages = {
    'en': {'name': 'English', 'native': 'English'},
    'zh': {'name': '中文', 'native': 'Chinese'},
    'es': {'name': 'Español', 'native': 'Spanish'},
    'fr': {'name': 'Français', 'native': 'French'},
    'ar': {'name': 'العربية', 'native': 'Arabic'},
    'ru': {'name': 'Русский', 'native': 'Russian'},
    'pt': {'name': 'Português', 'native': 'Portuguese'},
    'de': {'name': 'Deutsch', 'native': 'German'},
    'hi': {'name': 'हिंदी', 'native': 'Hindi'},
    'ta': {'name': 'தமிழ்', 'native': 'Tamil'},
  };


  Map<String, Map<String, String>> get languages => _languages;

  String get currentLanguageName => _languages[_currentLanguageCode]?['name'] ?? 'English';

  // Load saved language preference
  Future<void> loadLanguagePreference() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLanguage = prefs.getString('app_language');
      if (savedLanguage != null && _languages.containsKey(savedLanguage)) {
        _currentLanguageCode = savedLanguage;
        notifyListeners();
      }
    } catch (e) {
      debugPrint('Error loading language preference: $e');
    }
  }

  // Change language and persist
  Future<void> changeLanguage(String languageCode) async {
    if (_languages.containsKey(languageCode) && _currentLanguageCode != languageCode) {
      _currentLanguageCode = languageCode;

      // Notify listeneimmediately for instant UI update
      notifyListeners();

      // Save to SharedPreferences asynchronously without awaiting
      SharedPreferences.getInstance().then((prefs) {
        prefs.setString('app_language', languageCode);
      }).catchError((e) {
        debugPrint('Error saving language preference: $e');
      });
    }
  }

  // Get translation for a key
  String translate(String key) {
    return _translations[_currentLanguageCode]?[key] ??
           _translations['en']?[key] ??
           key;
  }

  // Short form for translation
  String t(String key) => translate(key);

  // Translations map
  final Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'create_new':'Create New',
      'app_name': 'MaxBillUp',
      'welcome': 'Welcome',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'update': 'Update',
      'search': 'Search',
      'settings': 'Settings',
      'logout': 'Logout',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'done': 'Done',
      'loading': 'Loading...',
      'coming_soon': 'Coming soon',
      'used': 'Used',
      'error': 'Error',
      'success': 'Success',
      'invoice': 'Invoice',

      // Navigation
      'home': 'Home',
      'sales': 'Sales',
      'stocks': 'Stocks',
      'reports': 'Reports',
      'menu': 'Menu',

      // Sales
      'new_sale': 'New Sale',
      'sale_all': 'Sale All',
      'quick_sale': 'Quick Sale',
      'saved_orders': 'Saved Orders',
      'save_order': 'Save Order',
      'complete_payment': 'Complete Payment',
      'add_to_cart': 'Add to Cart',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'payment_mode': 'Payment Mode',
      'cash': 'Cash',
      'online': 'Online',
      'credit': 'Credit',
      'split_payment': 'Split Payment',

      // Bill
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'total': 'Total',
      'grand_total': 'Grand Total',
      'amount_received': 'Amount Received',
      'change': 'Change',
      'customer': 'Customer',
      'add_customer': 'Add Customer',

      // Products/Stocks
      'products': 'Products',
      'category': 'Category',
      'addproduct': 'Add Product',
      'price': 'Price',
      'cost_price': 'Cost Price',
      'expense_names':'Expense Names',
      'mrp': 'MRP',
      'quantity': 'Quantity',
      'barcode': 'Barcode',
      'stock': 'Stock',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'low_stock': 'Low Stock',

      // Tax
      'tax_settings': 'Tax Settings',
      'add_tax': 'Add Tax',
      'tax_name': 'Tax Name',
      'tax_percentage': 'Tax %',
      'price_includes_tax': 'Tax Included in Price',
      'price_without_tax': 'Add Tax at Billing',
      'zero_rated_tax': 'No Tax Applied',
      'exempt_tax': 'Exempt from Tax',

      // Settings
      'profile': 'Profile',
      'business_details': 'Business Profile',
      'business_name': 'Business Name',
      'business_phone': 'Business Phone',
      'business_location': 'Business Location',
      'business_email': 'Business Email',
      'gstin': 'Tax No',
      'choose_language': 'Choose Language',
      'theme': 'Theme',
      'printer_setup': 'Printer Setup',
      'receipt_customization': 'Receipt Customization',
      'feature_settings': 'Feature Settings',
      'help': 'Help',
      'about': 'About',

      // Reports
      'daily_report': 'Daily Report',
      'monthly_report': 'Monthly Report',
      'sales_report': 'Sales Report',
      'stock_report': 'Stock Report',
      'tax_report': 'Tax Report',
      'profit_loss': 'Profit & Loss',

      // Messages
      'product_added': 'Product added successfully',
      'product_updated': 'Product updated successfully',
      'product_deleted': 'Product deleted successfully',
      'sale_completed': 'Sale completed successfully',
      'payment_successful': 'Payment successful',
      'payment_failed': 'Payment failed',
      'no_items_in_cart': 'No items in cart',
      'invalid_input': 'Invalid input',
      'required_field': 'This field is required',
      'confirm_delete': 'Are you sure you want to delete?',
      'saved_offline': 'Saved offline. Will sync when online.',
      'sync_completed': 'Sync completed',

      // Additional Pages
      'quotations': 'Quotations',
      'create_quotation': 'Create Quotation',
      'quotation_list': 'Quotation List',
      'convert_to_sale': 'Convert to Sale',
      'expenses': 'Expenses',
      'other_expenses': 'Other Expenses',
      'add_expense': 'Add Expense',
      'expense_category': 'Expense Type',
      'categories': 'Categories',
      'add_category': 'Add Category',
      'staff_management': 'Staff',
      'add_staff': 'Add Staff',
      'customer_management': 'Customers',
      'customers': 'Customers',
      'supplier': 'Supplier',
      'purchase': 'Purchase',
      'stock_purchase': 'Stock Purchase',
      'view': 'View',
      'print': 'Print',
      'share': 'Share',
      'receipt': 'Receipt',
      'date': 'Date',
      'time': 'Time',
      'from': 'From',
      'knowledge_base':'Knowledge Base',
      'video_tutorials':'Video Tutorials',
      'to': 'To',
      'all': 'All',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'custom': 'Custom',
      'apply': 'Apply',
      'reset': 'Reset',
      'export': 'Export',
      'download': 'Download',
      'upload': 'Upload',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'finish': 'Finish',
      'skip': 'Skip',
      'continue': 'Continue',
      'close': 'Close',
      'open': 'Open',
      'refresh': 'Refresh',
      'sync': 'Sync',
      'online_mode': 'Online Mode',
      'offline_mode': 'Offline Mode',
      'select': 'Select',
      'select_all': 'Select All',
      'deselect_all': 'Deselect All',
      'filter': 'Filter',
      'sort': 'Sort',
      'ascending': 'Ascending',
      'descending': 'Descending',
      'name': 'Name',
      'description': 'Description',
      'amount': 'Amount',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'pending': 'Pending',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'active': 'Active',
      'inactive': 'Inactive',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'phone': 'Phone',
      'email': 'Email',
      'address': 'Address',
      'city': 'City',
      'state': 'State',
      'country': 'Country',
      'pincode': 'Pincode',
      'notes': 'Notes',
      'remarks': 'Remarks',
      'status': 'Status',
      'action': 'Action',
      'actions': 'Actions',
      'details': 'Details',
      'summary': 'Summary',
      'billing': 'Billing',
      'shipping': 'Shipping',
      'payment': 'Payment',
      'order': 'Order',
      'orders': 'Orders',
      'item': 'Item',
      'items': 'Items',
      'unit': 'Unit',
      'rate': 'Rate',
      'gst': 'GST',
      'vat': 'VAT',
      'cgst': 'CGST',
      'sgst': 'SGST',
      'igst': 'IGST',
      'total_items': 'Total Items',
      'total_amount': 'Total Amount',
      'due_amount': 'Due Amount',
      'balance': 'Balance',
      'credit_limit': 'Credit Limit',
      'available': 'Available',
      'unavailable': 'Unavailable',

      // Additional UI strings
      'bill_history': 'Bill History',
      'bill_summary': 'Bill Summary',
      'bill_to': 'Bill To',
      'bill_cancelled': 'Bill Cancelled',
      'bill_description': 'Bill Description',
      'clear': 'Clear',
      'clear_order': 'Clear Order',
      'clear_all': 'Clear All',
      'report': 'Report',
      'no_products_found': 'No products found',
      'product_not_found': 'Product not found',
      'max_stock_reached': 'Max stock reached! ({0} available)',
      'enter_quantity': 'Enter Quantity',
      'saved': 'Saved',
      'quotation': 'Estimation / Quotation',
      'credit_notes': 'Return / Refunds',
      'add_credit_note': 'Add Credit Note',
      'credit_details': 'Credit Details',
      'available_credit_notes': 'Available Credit Notes',
      'bill_wise': 'Bill Wise',
      'customer_details': 'Customer Details',
      'add_customer_details': 'Add Customer Details',
      'add_new_customer': 'Add New Customer',
      'customer_name': 'Customer Name',
      'customer_phone': 'Customer Phone',
      'payment_method': 'Payment Method',
      'cash_payment': 'Cash Payment',
      'online_payment': 'Online Payment',
      'credit_payment': 'Credit Payment',
      'split': 'Split',
      'received': 'Received',
      'due': 'Due',
      'advance': 'Advance',
      'internal_note': 'Internal Note',
      'add_internal_note': 'Add Internal Note',
      'add_note': 'Add Note',
      'discount_percent': 'Discount (%)',
      'discount_amount': 'Discount Amount',
      'price_with_tax': 'Price with Tax',
      'tax_amount': 'Tax Amount',
      'payment_details': 'Payment Details',
      'billing_details': 'Billing Details',
      'proceed': 'Proceed',
      'discard': 'Discard',
      'confirm': 'Confirm',
      'warning': 'Warning',
      'are_you_sure': 'Are you sure?',
      'cannot_be_undone': 'This action cannot be undone',
      'discard_bill': 'Discard Bill',
      'are_you_sure_discard': 'Are you sure you want to discard this bill?',
      'delete_product': 'Delete Product',
      'are_you_sure_delete_product': 'Are you sure you want to delete this product?',
      'item_name': 'Item Name',
      'hsn_code': 'HSN Code',
      'unit_price': 'Unit Price',
      'selling_price': 'Selling Price',
      'stock_enabled': 'Stock Enabled',
      'current_stock': 'Current Stock',
      'low_stock_alert': 'Low Stock Alert',
      'min_stock': 'Min Stock',
      'max_stock': 'Max Stock',
      'reorder_level': 'Reorder Level',
      'category_name': 'Category Name',
      'add_category_name': 'Add Category Name',
      'delete_category': 'Delete Category',
      'are_you_sure_delete_category': 'Are you sure you want to delete this category?',
      'edit_product': 'Edit Product',
      'edit_category': 'Edit Category',
      'save_product': 'Save Product',
      'save_category': 'Save Category',
      'required': 'Required',
      'invalid': 'Invalid',
      'enter_valid_value': 'Enter valid value',
      'expense_name': 'Expense Name',
      'expense_amount': 'Expense Amount',
      'expense_date': 'Expense Date',
      'expense_type': 'Expense Type',
      'add_expense_category': 'Add Expense Category',
      'expense_categories': 'Expense Categories',
      'staff_name': 'Staff Name',
      'staff_phone': 'Staff Phone',
      'staff_email': 'Staff Email',
      'staff_role': 'Staff Role',
      'permissions': 'Permissions',
      'grant_permissions': 'Grant Permissions',
      'role': 'Role',
      'admin': 'Admin',
      'staff': 'Staff',
      'cashier': 'Cashier',
      'manager': 'Manager',
      'add_new_staff': 'Add New Staff',
      'edit_staff': 'Edit Staff',
      'delete_staff': 'Delete Staff',
      'are_you_sure_delete_staff': 'Are you sure you want to delete this staff member?',
      'login': 'Login',
      'email_phone': 'Email / Phone',
      'password': 'Password',
      'forgot_password': 'Forgot Password',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_in_with_google': 'Sign in with Google',
      'create_account': 'Create Account',
      'already_have_account': 'Already have an account?',
      'dont_have_account': 'Don\'t have an account?',
      'enter_email': 'Enter Email',
      'enter_phone': 'Enter Phone',
      'enter_password': 'Enter Password',
      'invalid_email': 'Invalid email',
      'invalid_phone': 'Invalid phone',
      'password_too_short': 'Password too short',
      'login_failed': 'Login failed',
      'signup_failed': 'Signup failed',
      'logout_confirm': 'Are you sure you want to logout?',
      'verify_email': 'Verify Email',
      'verify_email_message': 'Please check your inbox and verify your email address to continue.',
      'resend_email': 'Resend Email',
      'verification_email_sent': 'Verification email sent!',
      'approval_pending': 'Approval Pending',
      'admin_approval': 'Your email is verified! However, your account is waiting for Admin approval. Please ask your store admin to approve your account.',
      'google_sign_in_error': 'Google Sign In Error',
      'reset_link_sent': 'Reset link sent!',
      'error_sending_reset': 'Error sending reset link',
      'enter_email_reset': 'Enter email to reset password',
      'account_does_not_exist': 'Account does not exist.',
      'incorrect_password': 'Incorrect password.',
      'welcome_to': 'Welcome to',
      'login_staff': 'Login (Staff)',
      'by_proceeding_agree': 'By Proceeding, you agree to our ',
      'terms_and_conditions': 'Terms and Conditions',
      'refund_and_cancellation_policy': 'Refund and Cancellation Policy',
      'subscription_plan': 'Subscription Plan',
      'choose_plan': 'Choose Plan',
      'current_plan': 'Current Plan',
      'free_plan': 'Free Plan',
      'basic_plan': 'Basic Plan',
      'premium_plan': 'Premium Plan',
      'enterprise_plan': 'Enterprise Plan',
      'upgrade': 'Upgrade',
      'upgrade_now': 'Upgrade Now',
      'upgrade_to_premium': 'Upgrade to Premium',
      'features': 'Features',
      'per_month': 'Per Month',
      'per_year': 'Per Year',
      'best_value': 'Best Value',
      'most_popular': 'Most Popular',
      'contact_us': 'Contact Us',
      'terms_conditions': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'version': 'Version',
      'build': 'Build',
      'developed_by': 'Developed By',
      'powered_by': 'Powered By',
      'all_rights_reserved': 'All Rights Reserved',
      'language': 'Language',
      'currency': 'Currency',
      'timezone': 'Timezone',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'sound': 'Sound',
      'vibration': 'Vibration',
      'backup': 'Backup',
      'restore': 'Restore',
      'backup_restore': 'Backup & Restore',
      'create_backup': 'Create Backup',
      'restore_backup': 'Restore Backup',
      'last_backup': 'Last Backup',
      'no_backup': 'No Backup',
      'backup_success': 'Backup successful',
      'restore_success': 'Restore successful',
      'backup_failed': 'Backup failed',
      'restore_failed': 'Restore failed',
      'analytics': 'Analytics',
      'dashboard': 'Dashboard',
      'overview': 'Overview',
      'statistics': 'Statistics',
      'charts': 'Charts',
      'graphs': 'Graphs',
      'top_products': 'Top Products',
      'top_customers': 'Top Customers',
      'top_categories': 'Top Categories',
      'recent_sales': 'Recent Sales',
      'recent_orders': 'Recent Orders',
      'pending_orders': 'Pending Orders',
      'completed_orders': 'Completed Orders',
      'cancelled_orders': 'Cancelled Orders',
      'total_sales': 'Total Sales',
      'total_revenue': 'Total Revenue',
      'total_profit': 'Total Profit',
      'total_orders': 'Total Orders',
      'total_customers': 'Total Customers',
      'total_products': 'Total Products',
      'income': 'Income',
      'expense': 'Expense',
      'profit': 'Profit',
      'loss': 'Loss',
      'revenue': 'Revenue',
      'MAX Plus': 'MAX Plus',
      'decline': 'Decline',
      'percentage': 'Percentage',
      'change_from_last_month': 'Change from last month',
      'change_from_last_week': 'Change from last week',
      'last_7_days': 'Last 7 Days',
      'last_30_days': 'Last 30 Days',
      'last_90_days': 'Last 90 Days',
      'this_year': 'This Year',
      'last_year': 'Last Year',
      'custom_range': 'Custom Range',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'generate_report': 'Generate Report',
      'download_report': 'Download Report',
      'print_report': 'Print Report',
      'share_report': 'Share Report',
      'email_report': 'Email Report',
      'pdf_report': 'PDF Report',
      'excel_report': 'Excel Report',
      'report_generated': 'Report generated successfully',
      'report_failed': 'Report generation failed',
      'no_data': 'No data available',
      'no_results': 'No results found',
      'try_again': 'Try Again',
      'retry': 'Retry',
      'reload': 'Reload',
      'something_went_wrong': 'Something went wrong',
      'network_error': 'Network error',
      'server_error': 'Server error',
      'connection_failed': 'Connection failed',
      'please_check_internet': 'Please check your internet connection',
      'offline': 'Offline',
      'connecting': 'Connecting...',
      'syncing': 'Syncing...',
      'sync_failed': 'Sync failed',
      'sync_success': 'Synced successfully',
      'last_synced': 'Last synced',
      'never_synced': 'Never synced',
      'sync_now': 'Sync Now',
      'auto_sync': 'Auto Sync',
      'manual_sync': 'Manual Sync',
      'sync_settings': 'Sync Settings',
      'data_usage': 'Data Usage',
      'storage': 'Storage',
      'clear_cache': 'Clear Cache',
      'clear_data': 'Clear Data',
      'cache_cleared': 'Cache cleared',
      'data_cleared': 'Data cleared',
      'confirm_clear': 'Are you sure you want to clear?',
      'scanning': 'Scanning...',
      'scan_barcode': 'Scan Barcode',
      'scan_qr': 'Scan QR Code',
      'camera_permission': 'Camera Permission',
      'camera_permission_required': 'Camera permission is required',
      'grant_permission': 'Grant Permission',
      'permission_denied': 'Permission Denied',
      'enable_from_settings': 'Enable from Settings',
      'printer_not_found': 'Printer not found',
      'printer_connected': 'Printer connected',
      'printer_disconnected': 'Printer disconnected',
      'connecting_printer': 'Connecting to printer...',
      'print_settings': 'Print Settings',
      'paper_size': 'Paper Size',
      'print_quality': 'Print Quality',
      'copies': 'Copies',
      'print_preview': 'Print Preview',
      'printing': 'Printing...',
      'print_success': 'Printed successfully',
      'print_failed': 'Print failed',
      'bluetooth': 'Bluetooth',
      'wifi': 'WiFi',
      'usb': 'USB',
      'network': 'Network',
      'select_printer': 'Select Printer',
      'add_printer': 'Add Printer',
      'remove_printer': 'Remove Printer',
      'test_print': 'Test Print',
      'invoice_number': 'Invoice Number',
      'bill_number': 'Bill Number',
      'order_number': 'Order Number',
      'reference_number': 'Reference Number',
      'transaction_id': 'Transaction ID',
      'payment_id': 'Payment ID',
      'receipt_number': 'Receipt Number',
      'customer_copy': 'Customer Copy',
      'merchant_copy': 'Merchant Copy',
      'thank_you': 'Thank You',
      'visit_again': 'Visit Again',
      'terms': 'Terms',
      'signature': 'Signature',
      'authorized_signature': 'Authorized Signature',
      'stamp': 'Stamp',
      'company_stamp': 'Company Stamp',
      'powered_by_maxbillup': 'Powered by MaxBillUp',
      'generated_by': 'Generated By',
      'page': 'Page',
      'of': 'of',
      'sub_total': 'Sub Total',
      'taxable_amount': 'Taxable Amount',
      'tax_details': 'Tax Details',
      'round_off': 'Round Off',
      'net_amount': 'Net Amount',
      'amount_in_words': 'Amount in Words',
      'rupees': 'Rupees',
      'only': 'Only',
      'payment_status': 'Payment Status',
      'paid_amount': 'Paid Amount',
      'remaining_amount': 'Remaining Amount',
      'change_return': 'Change Return',
      'no_change': 'No Change',
      'payment_type': 'Payment Type',
      'card': 'Card',
      'upi': 'UPI',
      'wallet': 'Wallet',
      'cheque': 'Cheque',
      'bank_transfer': 'Bank Transfer',
      'other': 'Other',
      'specify': 'Specify',
      'add_existing':'Add Existing',
      'create_new':'Create New',

      // Menu.dart specific keys
      'billhistory': 'Manage Bills',
      'creditdetails': 'Credits / Dues',
      'expense_report': 'Expense Report',
      'nobillsfound': 'No bills found',
      'settle_bill': 'Settle Bill',
      'bill':'Bill',
      'by': 'By',
      'bill_not_found': 'Bill not found or deleted.',
      'created_by': 'Created by',
      'issued_on': 'Issued on',
      'invoice_items': 'Invoice items',
      'totalitems': 'Total items',
      'totalquantity': 'Total Qty',
      'totalamount': 'Total Amount',
      'refund': 'Refund',
      'preparing_print': 'Preparing print...',
      'printfailed': 'Print failed',
      'no_sales_credits': 'No sales credits found',
      'no_matching_customers': 'No matching customefound',
      'total_sales_credit': 'Total Sales Credit',
      'no_purchase_credits': 'No purchase credits found',
      'no_matching_purchase_credits': 'No matching purchase credits',
      'total_purchase_credit': 'Total Purchase Credit',
      'unknown_supplier': 'Unknown Supplier',
      'purchase_credit_note': 'Purchase Credit Note',
      'credit_note_not_found': 'Credit note not found',
      'areyousure': 'Are you sure?',
      'mode': 'Mode',
      'addnewcustomer': 'Add New Customer',
      'existing_customer': 'Existing Customer',
      'name_phone_required': 'Please enter name and phone number',
      'no_customers_found': 'No Customer Found',
      'staffmanagement': 'Staff',
      'addnewstaff': 'Add New Staff',
      'savestaff': 'Save Staff',
      'staff_added_success': 'Staff added successfully',
      'sale_return': 'Sale Return',
      'thismonth': 'This Month',
      'lastmonth': 'Last Month',
      'invoicenumber': 'Invoice No.',
      'customerdetails': 'Customer Details',
      'cancel_bill': 'Cancel Bill',
      'enter_valid_amount': 'Please enter a valid amount',
      'payment_settled': 'Payment settled successfully',
      'payment_recorded': 'Payment recorded',
      'error_processing_payment': 'Error processing payment',
      'add_discount': 'Add Discount',
      'enter_note': 'Enter note...',
      'bill_updated_success': 'Bill updated successfully',
      'error_updating_bill': 'Error updating bill',
      ''

      // Reports page keys
      'analytics_overview': 'Analytics & Overview',
      'daybook_today': 'DayBook (Today)',
      'sales_transactions': 'Sales & Transactions',
      'item_sales_report': 'Item Sales Report',
      'inventory_products': 'Inventory & Products',
      'low_stock_products': 'Low Stock Items',
      'financials_tax': 'Financials & Tax',
      'hsn_report': 'HSN Report',
      'staff_sale_report': 'Staff Sale Report',
      'no_report_access': 'No Report Access',
      'no_report_permission_msg': 'You don\'t have permission to view any reports. Contact your administrator.',
      'hour': 'Hour',
      'currency_symbol': '',

      // Expenses page keys
      'new_expense': 'New Expense',
      'expense_details': 'Expense Details',
      'new_other_expense': 'New Other Expense',

      // Stock purchase keys
      'new_stock_purchase': 'New Stock Purchase',
      'purchase_details': 'Purchase Details',

      // Products page keys
      'filter_by_stock': 'Filter By Stock',
      'all_products': 'All Products',
      'low_stock_filter': 'Low Stock (< 10)',
      'remove': 'Remove',
      'enter_valid_quantity': 'Please enter a valid quantity',

      // Category keys
      'category_updated_success': 'Category updated successfully',
      'category_deleted_success': 'Category deleted successfully',
      'are_you_sure_delete': 'Are you sure you want to delete',

      // AddProduct keys
      'add_new_unit': 'Add New Unit',

      // Profile/Settings keys
      'upgrade_plan': 'Upgrade Plan',
      'restricted_access': 'Restricted Access',

      // Bill keys
      'total_payable': 'Total Payable',
      'new_customer': 'New Customer',
      'select_customer': 'Select Customer',
      'total_bill_amount': 'Total Bill Amount',
      'paid_so_far': 'Paid So Far',
      'total_bill': 'Total Bill',

      // Quotation keys
      'share_error': 'Share Error',
      'no_printer_selected': 'No Printer Selected',
      'select_printer_from_settings': 'Please select a printer from Settings > Printer Setup before printing.',
      'print_error': 'Print Error',

      // TaxSettings keys
      'create_type': 'Create Type',
      'add_tax_rate': 'Add Tax Rate',
      'update_settings': 'Update Settings',

      // StaffManagement keys
      'no_staff_members': 'No staff membeyet',
      'invite_to_start': 'Invite someone to get started',
      'invite_new_staff': 'Invite New Staff',
      'send_invite': 'Send Invite',
      'edit_staff_member': 'Edit Staff Member',
      'remove_staff': 'Remove Staff',

      // QuotationsList keys
      'no_quotations_found': 'No quotations found',
      'date_newest_first': 'Date: Newest First',
      'date_oldest_first': 'Date: Oldest First',
      'amount_high_to_low': 'Amount: High to Low',
      'amount_low_to_high': 'Amount: Low to High',
      'settled': 'Settled',

      // Additional common keys
      'fill_required_fields': 'Please fill in required fields',
      'expense_saved_success': 'Expense saved successfully',
      'enter_category_name': 'Please enter a category name',
      'category_added_success': 'Category added successfully',
      'category_exists': 'Category already exists',

      // Saved ordekeys
      'order_deleted': 'Order deleted',
      'delete_order': 'Delete Order',
      'no_saved_orders': 'No Saved Orders',

      // BusinessDetailsPage keys
      'complete_profile_title': 'Complete Your Profile',
      'complete_profile_subtitle': 'Please provide your business details to get started',
      'personaldetails': 'Personal Details',
      'your_name': 'Your Name',
      'enter_full_name': 'Enter your full name',
      'name_required': 'Name is required',
      'your_phone': 'Your Phone Number',
      'phone_required': 'Phone is required',
      'phone_invalid_10_digit': 'Enter valid 10-digit phone',
      'businessdetails': 'Business Details',
      'businessname': 'Business Name',
      'enter_business_name': 'Enter your business name',
      'business_name_required': 'Business name is required',
      'businessphone': 'Business Phone Number',
      'enter_business_phone': 'Enter business phone number',
      'business_phone_required': 'Business phone is required',
      'gstin_optional': 'GSTIN (Optional)',
      'enter_gstin': 'Enter GSTIN number',
      'businesslocation': 'Business Location',
      'enter_business_location': 'Enter your business location',
      'business_location_required': 'Business location is required',
      'complete_registration': 'Complete Registration',
      'business_registered_success': 'Business registered successfully!',
      'failed_to_save': 'Failed to save',

      // SubscriptionPlanPage keys
      'subscription_expiry': 'Expires',
      'permonth': '/month',
      'six_months': '6 Months',
      'peryear': '/year',
      'save_20': 'SAVE 20%',
      'perperiod': '/period',
      'full_feature_comparison': 'Full Feature Comparison',
      'freeplan': 'Free',
      'bulk_inventory': 'Bulk Inventory',
      'logo_on_bill': 'Logo on Bill',
      'customer_credit': 'Customer Credit',
      'edit_bill': 'Edit Bill',
      'taxreport': 'Tax Report',
      'import_contacts': 'Import Contacts',
      'pos_billing': 'POS Billing',
      'cloud_storage': 'Cloud Storage',
      'currentplan': 'Current Plan',
      'pay_now': 'Pay Now',
      'paymentsuccessful': 'Payment Successful! Plan Upgraded.',
      'paymentfailed': 'Payment Failed',

      // BarcodeScanner keys
      'scanbarcode': 'Scan Barcode',
      'product_added_scanned': 'Product added',
      'total_scanned': 'Total scanned',
      'products_scanned': 'Products Scanned',
      'scan_multiple_products': 'Scan multiple products\nPress back when done',

      // Language settings keys
      'available_languages': 'Available Languages',
      'language_changed_to': 'Language changed to',
      'common_translations': 'Common Translations',

      // Additional keys
      'nodata': 'No data available',
      'daybook': 'DayBook',
      'sales_summary': 'Sales Summary',
      'customername': 'Customer Name',
      'customerphone': 'Customer Phone',

      // AddProduct page localization keys
      'item_information': 'Item Information',
      'leave_blank_for_price': 'Leave blank for price at time of sale.',
      'more_details': 'More Details',
      'cost_price_optional': 'Cost Price (Optional)',
      'mrp_optional': 'MRP (Optional)',
      'product_code': 'Product Code',
      'generate': 'Generate',
      'find': 'Find',
      'hsn_scn': 'Hsn/scn',
      'barcode_info': 'To add barcode from external barcode reader, tap on barcode field and scan barcode',
      'stock_unit': 'Stock Unit',
      'this_field_is_required': 'This field is required',

      // Category.dart specific keys
      'search_categories': 'Search categories...',
      'no_categories_yet': 'No categories yet',
      'add_first_category': 'Add your first category to organize products',
      'no_categories_found': 'No categories found',
      'try_searching_keywords': 'Try searching with different keywords',
      'add_product': 'Add Product',
      'create_new_product': 'Create New Product',
      'add_existing_product': 'Add Existing Product',
      'no_products_available': 'No products available',
      'current': 'Current',
      'price_on_sale': 'Price on Sale',
      'added_to': 'Added to',
    },

    'hi': {
      // Common
      'app_name': 'मैक्सबिलअप',
      'welcome': 'स्वागत है',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'add': 'जोड़ें',
      'update': 'अपडेट करें',
      'search': 'खोजें',
      'settings': 'सेटिंग्स',
      'logout': 'लॉग आउट',
      'yes': 'हां',
      'no': 'नहीं',
      'ok': 'ठीक है',
      'done': 'हो गया',
      'loading': 'लोड हो रहा है...',
      'coming_soon': 'जल्द आ रहा है',
      'used': 'उपयोग किया गया',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'invoice': 'चालान',

      // Navigation
      'home': 'होम',
      'sales': 'बिक्री',
      'stocks': 'स्टॉक',
      'reports': 'रिपोर्ट्स',
      'menu': 'मेन्यू',

      // Sales
      'new_sale': 'नई बिक्री',
      'sale_all': 'सभी बिक्री',
      'quick_sale': 'त्वरित बिक्री',
      'saved_orders': 'सहेजे गए ऑर्डर',
      'save_order': 'ऑर्डर सहेजें',
      'complete_payment': 'भुगतान पूरा करें',
      'add_to_cart': 'कार्ट में जोड़ें',
      'cart': 'कार्ट',
      'checkout': 'चेकआउट',
      'payment_mode': 'भुगतान मोड',
      'cash': 'नकद',
      'online': 'ऑनलाइन',
      'credit': 'क्रेडिट',
      'split_payment': 'विभाजित भुगतान',

      // Bill
      'subtotal': 'सबटोटल',
      'discount': 'छूट',
      'tax': 'टैक्स',
      'total': 'कुल',
      'grand_total': 'कुल योग',
      'amount_received': 'प्राप्त राशि',
      'change': 'वापसी',
      'customer': 'ग्राहक',
      'add_customer': 'ग्राहक जोड़ें',

      // Products/Stocks
      'products': 'उत्पाद',
      'category': 'श्रेणी',
      'addproduct': 'उत्पाद जोड़ें',
      'price': 'मूल्य',
      'cost_price': 'लागत मूल्य',
      'mrp': 'एमआरपी',
      'quantity': 'मात्रा',
      'barcode': 'बारकोड',
      'stock': 'स्टॉक',
      'in_stock': 'स्टॉक में',
      'out_of_stock': 'स्टॉक खत्म',
      'low_stock': 'कम स्टॉक',

      // Tax
      'tax_settings': 'टैक्स सेटिंग्स',
      'add_tax': 'टैक्स जोड़ें',
      'tax_name': 'टैक्स नाम',
      'tax_percentage': 'टैक्स %',
      'price_includes_tax': 'मूल्य में टैक्स शामिल',
      'price_without_tax': 'मूल्य टैक्स रहित',
      'zero_rated_tax': 'शून्य दर टैक्स',
      'exempt_tax': 'टैक्स मुक्त',

      // Settings
      'profile': 'प्रोफ़ाइल',
      'business_details': 'व्यवसाय विवरण',
      'business_name': 'व्यवसाय का नाम',
      'business_phone': 'व्यवसाय फोन',
      'business_location': 'व्यवसाय स्थान',
      'business_email': 'व्यवसाय ईमेल',
      'gstin': 'जीएसटीआईएन',
      'choose_language': 'भाषा चुनें',
      'theme': 'थीम',
      'printer_setup': 'प्रिंटर सेटअप',
      'receipt_customization': 'रसीद अनुकूलन',
      'feature_settings': 'फीचर सेटिंग्स',
      'help': 'मदद',
      'about': 'के बारे में',

      // Reports
      'daily_report': 'दैनिक रिपोर्ट',
      'monthly_report': 'मासिक रिपोर्ट',
      'sales_report': 'बिक्री रिपोर्ट',
      'stock_report': 'स्टॉक रिपोर्ट',
      'tax_report': 'टैक्स रिपोर्ट',
      'profit_loss': 'लाभ और हानि',

      // Messages
      'product_added': 'उत्पाद सफलतापूर्वक जोड़ा गया',
      'product_updated': 'उत्पाद अपडेट किया गया',
      'product_deleted': 'उत्पाद हटाया गया',
      'sale_completed': 'बिक्री पूरी हुई',
      'payment_successful': 'भुगतान सफल',
      'payment_failed': 'भुगतान विफल',
      'no_items_in_cart': 'कार्ट में कोई आइटम नहीं',
      'invalid_input': 'अमान्य इनपुट',
      'required_field': 'यह फ़ील्ड आवश्यक है',
      'confirm_delete': 'क्या आप वाकई हटाना चाहते हैं?',
      'saved_offline': 'ऑफ़लाइन सहेजा गया। ऑनलाइन होने पर सिंक होगा।',
      'sync_completed': 'सिंक पूरा हुआ',

      // Additional Pages
      'quotations': 'कोटेशन',
      'create_quotation': 'कोटेशन बनाएं',
      'quotation_list': 'कोटेशन सूची',
      'convert_to_sale': 'बिक्री में बदलें',
      'expenses': 'खर्च',
      'other_expenses': 'अन्य खर्च',
      'add_expense': 'खर्च जोड़ें',
      'expense_category': 'खर्च श्रेणी',
      'categories': 'श्रेणियाँ',
      'add_category': 'श्रेणी जोड़ें',
      'staff_management': 'कर्मचारी प्रबंधन',
      'add_staff': 'कर्मचारी जोड़ें',
      'customer_management': 'ग्राहक प्रबंधन',
      'customers': 'ग्राहक',
      'supplier': 'आपूर्तिकर्ता',
      'purchase': 'खरीद',
      'stock_purchase': 'स्टॉक खरीद',
      'view': 'देखें',
      'print': 'प्रिंट करें',
      'share': 'साझा करें',
      'receipt': 'रसीद',
      'date': 'तारीख',
      'time': 'समय',
      'from': 'से',
      'to': 'तक',
      'all': 'सभी',
      'today': 'आज',
      'yesterday': 'कल',
      'this_week': 'इस सप्ताह',
      'this_month': 'इस महीने',
      'custom': 'कस्टम',
      'apply': 'लागू करें',
      'reset': 'रीसेट करें',
      'export': 'निर्यात करें',
      'download': 'डाउनलोड करें',
      'upload': 'अपलोड करें',
      'back': 'वापस',
      'next': 'अगला',
      'previous': 'पिछला',
      'finish': 'समाप्त',
      'skip': 'छोड़ें',
      'continue': 'जारी रखें',
      'close': 'बंद करें',
      'open': 'खोलें',
      'refresh': 'ताज़ा करें',
      'sync': 'सिंक करें',
      'online_mode': 'ऑनलाइन मोड',
      'offline_mode': 'ऑफ़लाइन मोड',
      'select': 'चुनें',
      'select_all': 'सभी चुनें',
      'deselect_all': 'सभी अचयनित करें',
      'filter': 'फ़िल्टर',
      'sort': 'क्रमबद्ध करें',
      'ascending': 'आरोही',
      'descending': 'अवरोही',
      'name': 'नाम',
      'description': 'विवरण',
      'amount': 'राशि',
      'paid': 'भुगतान किया',
      'unpaid': 'अवैतनिक',
      'pending': 'लंबित',
      'completed': 'पूरा',
      'cancelled': 'रद्द',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'enabled': 'सक्षम',
      'disabled': 'अक्षम',
      'phone': 'फोन',
      'email': 'ईमेल',
      'address': 'पता',
      'city': 'शहर',
      'state': 'राज्य',
      'country': 'देश',
      'pincode': 'पिनकोड',
      'notes': 'नोट्स',
      'remarks': 'टिप्पणियाँ',
      'status': 'स्थिति',
      'action': 'कार्रवाई',
      'actions': 'कार्रवाइयाँ',
      'details': 'विवरण',
      'summary': 'सारांश',
      'billing': 'बिलिंग',
      'shipping': 'शिपिंग',
      'payment': 'भुगतान',
      'order': 'ऑर्डर',
      'orders': 'ऑर्डर',
      'item': 'आइटम',
      'items': 'आइटम',
      'unit': 'इकाई',
      'rate': 'दर',
      'gst': 'जीएसटी',
      'vat': 'वैट',
      'cgst': 'सीजीएसटी',
      'sgst': 'एसजीएसटी',
      'igst': 'आईजीएसटी',
      'total_items': 'कुल आइटम',
      'total_amount': 'कुल राशि',
      'due_amount': 'बकाया राशि',
      'balance': 'बैलेंस',
      'credit_limit': 'क्रेडिट लिमिट',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',

      // Additional UI strings
      'bill_history': 'बिल इतिहास',
      'bill_summary': 'बिल सारांश',
      'bill_to': 'बिल प्राप्तकर्ता',
      'bill_cancelled': 'बिल रद्द',
      'bill_description': 'बिल विवरण',
      'clear': 'साफ़ करें',
      'clear_order': 'ऑर्डर साफ़ करें',
      'clear_all': 'सभी साफ़ करें',
      'report': 'रिपोर्ट',
      'no_products_found': 'कोई उत्पाद नहीं मिला',
      'product_not_found': 'उत्पाद नहीं मिला',
      'max_stock_reached': 'अधिकतम स्टॉक सीमा! ({0} उपलब्ध)',
      'enter_quantity': 'मात्रा दर्ज करें',
      'saved': 'सहेजा गया',
      'quotation': 'कोटेशन',
      'credit_notes': 'क्रेडिट नोट',
      'add_credit_note': 'क्रेडिट नोट जोड़ें',
      'credit_details': 'क्रेडिट विवरण',
      'available_credit_notes': 'उपलब्ध क्रेडिट नोट',
      'bill_wise': 'बिल वार',
      'customer_details': 'ग्राहक विवरण',
      'add_customer_details': 'ग्राहक विवरण जोड़ें',
      'add_new_customer': 'नया ग्राहक जोड़ें',
      'customer_name': 'ग्राहक का नाम',
      'customer_phone': 'ग्राहक फोन',
      'payment_method': 'भुगतान विधि',
      'cash_payment': 'नकद भुगतान',
      'online_payment': 'ऑनलाइन भुगतान',
      'credit_payment': 'क्रेडिट भुगतान',
      'split': 'विभाजित',
      'received': 'प्राप्त',
      'due': 'बकाया',
      'advance': 'अग्रिम',
      'internal_note': 'आंतरिक नोट',
      'add_internal_note': 'आंतरिक नोट जोड़ें',
      'add_note': 'नोट जोड़ें',
      'discount_percent': 'छूट (%)',
      'discount_amount': 'छूट राशि',
      'price_with_tax': 'टैक्स सहित मूल्य',
      'tax_amount': 'टैक्स राशि',
      'payment_details': 'भुगतान विवरण',
      'billing_details': 'बिलिंग विवरण',
      'proceed': 'आगे बढ़ें',
      'discard': 'छोड़ें',
      'confirm': 'पुष्टि करें',
      'warning': 'चेतावनी',
      'are_you_sure': 'क्या आप सुनिश्चित हैं?',
      'cannot_be_undone': 'यह क्रिया पूर्ववत नहीं की जा सकती',
      'discard_bill': 'बिल छोड़ें',
      'are_you_sure_discard': 'क्या आप इस बिल को छोड़ना चाहते हैं?',
      'delete_product': 'उत्पाद हटाएं',
      'are_you_sure_delete_product': 'क्या आप इस उत्पाद को हटाना चाहते हैं?',
      'item_name': 'आइटम का नाम',
      'hsn_code': 'एचएसएन कोड',
      'unit_price': 'इकाई मूल्य',
      'selling_price': 'विक्रय मूल्य',
      'stock_enabled': 'स्टॉक सक्षम',
      'current_stock': 'वर्तमान स्टॉक',
      'low_stock_alert': 'कम स्टॉक अलर्ट',
      'min_stock': 'न्यूनतम स्टॉक',
      'max_stock': 'अधिकतम स्टॉक',
      'reorder_level': 'पुन: ऑर्डर स्तर',
      'category_name': 'श्रेणी नाम',
      'add_category_name': 'श्रेणी नाम जोड़ें',
      'delete_category': 'श्रेणी हटाएं',
      'are_you_sure_delete_category': 'क्या आप इस श्रेणी को हटाना चाहते हैं?',
      'edit_product': 'उत्पाद संपादित करें',
      'edit_category': 'श्रेणी संपादित करें',
      'save_product': 'उत्पाद सहेजें',
      'save_category': 'श्रेणी सहेजें',
      'required': 'आवश्यक',
      'invalid': 'अमान्य',
      'enter_valid_value': 'मान्य मान दर्ज करें',
      'expense_name': 'खर्च का नाम',
      'expense_amount': 'खर्च राशि',
      'expense_date': 'खर्च तिथि',
      'expense_type': 'खर्च प्रकार',
      'add_expense_category': 'खर्च श्रेणी जोड़ें',
      'expense_categories': 'खर्च श्रेणियाँ',
      'staff_name': 'कर्मचारी का नाम',
      'staff_phone': 'कर्मचारी फोन',
      'staff_email': 'कर्मचारी ईमेल',
      'staff_role': 'कर्मचारी भूमिका',
      'permissions': 'अनुमतियाँ',
      'grant_permissions': 'अनुमतियाँ दें',
      'role': 'भूमिका',
      'admin': 'व्यवस्थापक',
      'staff': 'कर्मचारी',
      'cashier': 'कैशियर',
      'manager': 'प्रबंधक',
      'add_new_staff': 'नया कर्मचारी जोड़ें',
      'edit_staff': 'कर्मचारी संपादित करें',
      'delete_staff': 'कर्मचारी हटाएं',
      'are_you_sure_delete_staff': 'क्या आप इस कर्मचारी को हटाना चाहते हैं?',
      'login': 'लॉगिन',
      'email_phone': 'ईमेल / फोन',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए',
      'sign_in': 'साइन इन',
      'sign_up': 'साइन अप',
      'sign_in_with_google': 'Google से साइन इन करें',
      'create_account': 'खाता बनाएं',
      'already_have_account': 'पहले से खाता है?',
      'dont_have_account': 'खाता नहीं है?',
      'enter_email': 'ईमेल दर्ज करें',
      'enter_phone': 'फोन दर्ज करें',
      'enter_password': 'पासवर्ड दर्ज करें',
      'invalid_email': 'अमान्य ईमेल',
      'invalid_phone': 'अमान्य फोन',
      'password_too_short': 'पासवर्ड बहुत छोटा',
      'login_failed': 'लॉगिन विफल',
      'signup_failed': 'साइनअप विफल',
      'logout_confirm': 'क्या आप लॉगआउट करना चाहते हैं?',
      'verify_email': 'ईमेल सत्यापित करें',
      'verify_email_message': 'जारी रखने के लिए कृपया अपना इनबॉक्स जांचें और अपना ईमेल पता सत्यापित करें।',
      'resend_email': 'ईमेल पुनः भेजें',
      'verification_email_sent': 'सत्यापन ईमेल भेजा गया!',
      'approval_pending': 'अनुमोदन लंबित',
      'admin_approval': 'आपका ईमेल सत्यापित हो गया है! हालांकि, आपका खाता व्यवस्थापक अनुमोदन की प्रतीक्षा कर रहा है। कृपया अपने स्टोर व्यवस्थापक से अपने खाते को स्वीकृत करने के लिए कहें।',
      'google_sign_in_error': 'Google साइन इन त्रुटि',
      'reset_link_sent': 'रीसेट लिंक भेजा गया!',
      'error_sending_reset': 'रीसेट लिंक भेजने में त्रुटि',
      'enter_email_reset': 'पासवर्ड रीसेट करने के लिए ईमेल दर्ज करें',
      'account_does_not_exist': 'खाता मौजूद नहीं है।',
      'incorrect_password': 'गलत पासवर्ड।',
      'welcome_to': 'आपका स्वागत है',
      'login_staff': 'लॉगिन (कर्मचारी)',
      'by_proceeding_agree': 'आगे बढ़ने से, आप हमारी ',
      'terms_and_conditions': 'नियम और शर्तें',
      'refund_and_cancellation_policy': 'धनवापसी और रद्दीकरण नीति',
      'subscription_plan': 'सदस्यता योजना',
      'choose_plan': 'योजना चुनें',
      'current_plan': 'वर्तमान योजना',
      'free_plan': 'मुफ्त योजना',
      'basic_plan': 'बेसिक योजना',
      'premium_plan': 'प्रीमियम योजना',
      'enterprise_plan': 'एंटरप्राइज योजना',
      'upgrade': 'अपग्रेड',
      'upgrade_now': 'अभी अपग्रेड करें',
      'upgrade_to_premium': 'प्रीमियम में अपग्रेड करें',
      'features': 'विशेषताएँ',
      'per_month': 'प्रति माह',
      'per_year': 'प्रति वर्ष',
      'best_value': 'सर्वोत्तम मूल्य',
      'most_popular': 'सबसे लोकप्रिय',
      'contact_us': 'संपर्क करें',
      'terms_conditions': 'नियम और शर्तें',
      'privacy_policy': 'गोपनीयता नीति',
      'version': 'संस्करण',
      'build': 'बिल्ड',
      'developed_by': 'द्वारा विकसित',
      'powered_by': 'द्वारा संचालित',
      'all_rights_reserved': 'सर्वाधिकार सुरक्षित',
      'language': 'भाषा',
      'currency': 'मुद्रा',
      'timezone': 'समय क्षेत्र',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाएं सक्षम करें',
      'sound': 'ध्वनि',
      'vibration': 'कंपन',
      'backup': 'बैकअप',
      'restore': 'पुनर्स्थापित',
      'backup_restore': 'बैकअप और पुनर्स्थापना',
      'create_backup': 'बैकअप बनाएं',
      'restore_backup': 'बैकअप पुनर्स्थापित करें',
      'last_backup': 'अंतिम बैकअप',
      'no_backup': 'कोई बैकअप नहीं',
      'backup_success': 'बैकअप सफल',
      'restore_success': 'पुनर्स्थापना सफल',
      'backup_failed': 'बैकअप विफल',
      'restore_failed': 'पुनर्स्थापना विफल',
      'analytics': 'विश्लेषण',
      'dashboard': 'डैशबोर्ड',
      'overview': 'अवलोकन',
      'statistics': 'सांख्यिकी',
      'charts': 'चार्ट',
      'graphs': 'ग्राफ',
      'top_products': 'शीर्ष उत्पाद',
      'top_customers': 'शीर्ष ग्राहक',
      'top_categories': 'शीर्ष श्रेणियाँ',
      'recent_sales': 'हालिया बिक्री',
      'recent_orders': 'हालिया ऑर्डर',
      'pending_orders': 'लंबित ऑर्डर',
      'completed_orders': 'पूर्ण ऑर्डर',
      'cancelled_orders': 'रद्द ऑर्डर',
      'total_sales': 'कुल बिक्री',
      'total_revenue': 'कुल राजस्व',
      'total_profit': 'कुल लाभ',
      'total_orders': 'कुल ऑर्डर',
      'total_customers': 'कुल ग्राहक',
      'total_products': 'कुल उत्पाद',
      'income': 'आय',
      'expense': 'व्यय',
      'profit': 'लाभ',
      'loss': 'हानि',
      'revenue': 'राजस्व',
      'MAX Plus': 'वृद्धि',
      'decline': 'गिरावट',
      'percentage': 'प्रतिशत',
      'change_from_last_month': 'पिछले महीने से परिवर्तन',
      'change_from_last_week': 'पिछले सप्ताह से परिवर्तन',
      'last_7_days': 'पिछले 7 दिन',
      'last_30_days': 'पिछले 30 दिन',
      'last_90_days': 'पिछले 90 दिन',
      'this_year': 'इस वर्ष',
      'last_year': 'पिछले वर्ष',
      'custom_range': 'कस्टम रेंज',
      'start_date': 'प्रारंभ तिथि',
      'end_date': 'समाप्ति तिथि',
      'generate_report': 'रिपोर्ट बनाएं',
      'download_report': 'रिपोर्ट डाउनलोड करें',
      'print_report': 'रिपोर्ट प्रिंट करें',
      'share_report': 'रिपोर्ट साझा करें',
      'email_report': 'रिपोर्ट ईमेल करें',
      'pdf_report': 'पीडीएफ रिपोर्ट',
      'excel_report': 'एक्सेल रिपोर्ट',
      'report_generated': 'रिपोर्ट सफलतापूर्वक बनाई गई',
      'report_failed': 'रिपोर्ट बनाना विफल',
      'no_data': 'कोई डेटा उपलब्ध नहीं',
      'no_results': 'कोई परिणाम नहीं मिला',
      'try_again': 'पुनः प्रयास करें',
      'retry': 'पुनः प्रयास',
      'reload': 'पुनः लोड करें',
      'something_went_wrong': 'कुछ गलत हो गया',
      'network_error': 'नेटवर्क त्रुटि',
      'server_error': 'सर्वर त्रुटि',
      'connection_failed': 'कनेक्शन विफल',
      'please_check_internet': 'कृपया अपना इंटरनेट कनेक्शन जांचें',
      'offline': 'ऑफ़लाइन',
      'connecting': 'कनेक्ट हो रहा है...',
      'syncing': 'सिंक हो रहा है...',
      'sync_failed': 'सिंक विफल',
      'sync_success': 'सफलतापूर्वक सिंक किया गया',
      'last_synced': 'अंतिम सिंक',
      'never_synced': 'कभी सिंक नहीं किया गया',
      'sync_now': 'अभी सिंक करें',
      'auto_sync': 'ऑटो सिंक',
      'manual_sync': 'मैनुअल सिंक',
      'sync_settings': 'सिंक सेटिंग्स',
      'data_usage': 'डेटा उपयोग',
      'storage': 'स्टोरेज',
      'clear_cache': 'कैश साफ़ करें',
      'clear_data': 'डेटा साफ़ करें',
      'cache_cleared': 'कैश साफ़ किया गया',
      'data_cleared': 'डेटा साफ़ किया गया',
      'confirm_clear': 'क्या आप साफ़ करना चाहते हैं?',
      'scanning': 'स्कैन हो रहा है...',
      'scan_barcode': 'बारकोड स्कैन करें',
      'scan_qr': 'क्यूआर कोड स्कैन करें',
      'camera_permission': 'कैमरा अनुमति',
      'camera_permission_required': 'कैमरा अनुमति आवश्यक है',
      'grant_permission': 'अनुमति दें',
      'permission_denied': 'अनुमति अस्वीकृत',
      'enable_from_settings': 'सेटिंग्स से सक्षम करें',
      'printer_not_found': 'प्रिंटर नहीं मिला',
      'printer_connected': 'प्रिंटर कनेक्ट हुआ',
      'printer_disconnected': 'प्रिंटर डिस्कनेक्ट हुआ',
      'connecting_printer': 'प्रिंटर से कनेक्ट हो रहा है...',
      'print_settings': 'प्रिंट सेटिंग्स',
      'paper_size': 'पेपर साइज़',
      'print_quality': 'प्रिंट गुणवत्ता',
      'copies': 'प्रतियां',
      'print_preview': 'प्रिंट पूर्वावलोकन',
      'printing': 'प्रिंट हो रहा है...',
      'print_success': 'सफलतापूर्वक प्रिंट किया गया',
      'print_failed': 'प्रिंट विफल',
      'bluetooth': 'ब्लूटूथ',
      'wifi': 'वाईफाई',
      'usb': 'यूएसबी',
      'network': 'नेटवर्क',
      'select_printer': 'प्रिंटर चुनें',
      'add_printer': 'प्रिंटर जोड़ें',
      'remove_printer': 'प्रिंटर हटाएं',
      'test_print': 'टेस्ट प्रिंट',
      'invoice_number': 'चालान संख्या',
      'bill_number': 'बिल संख्या',
      'order_number': 'ऑर्डर संख्या',
      'reference_number': 'संदर्भ संख्या',
      'transaction_id': 'लेनदेन आईडी',
      'payment_id': 'भुगतान आईडी',
      'receipt_number': 'रसीद संख्या',
      'customer_copy': 'ग्राहक प्रति',
      'merchant_copy': 'व्यापारी प्रति',
      'thank_you': 'धन्यवाद',
      'visit_again': 'फिर आएं',
      'terms': 'शर्तें',
      'signature': 'हस्ताक्षर',
      'authorized_signature': 'अधिकृत हस्ताक्षर',
      'stamp': 'मुहर',
      'company_stamp': 'कंपनी मुहर',
      'powered_by_maxbillup': 'MaxBillUp द्वारा संचालित',
      'generated_by': 'द्वारा बनाया गया',
      'page': 'पृष्ठ',
      'of': 'का',
      'sub_total': 'उप योग',
      'taxable_amount': 'कर योग्य राशि',
      'tax_details': 'कर विवरण',
      'round_off': 'राउंड ऑफ',
      'net_amount': 'शुद्ध राशि',
      'amount_in_words': 'शब्दों में राशि',
      'rupees': 'रुपये',
      'only': 'मात्र',
      'payment_status': 'भुगतान स्थिति',
      'paid_amount': 'भुगतान की गई राशि',
      'remaining_amount': 'शेष राशि',
      'change_return': 'वापसी',
      'no_change': 'कोई वापसी नहीं',
      'payment_type': 'भुगतान प्रकार',
      'card': 'कार्ड',
      'upi': 'यूपीआई',
      'wallet': 'वॉलेट',
      'cheque': 'चेक',
      'bank_transfer': 'बैंक ट्रांसफर',
      'other': 'अन्य',
      'specify': 'निर्दिष्ट करें',

      // Menu.dart specific keys
      'billhistory': 'बिल इतिहास',
      'creditdetails': 'क्रेडिट विवरण',
      'expense_report': 'खर्च रिपोर्ट',
      'nobillsfound': 'कोई बिल नहीं मिला',
      'settle_bill': 'बिल निपटाएं',
      'by': 'द्वारा',
      'bill_not_found': 'बिल नहीं मिला या हटा दिया गया।',
      'created_by': 'द्वारा बनाया गया',
      'issued_on': 'जारी किया गया',
      'invoice_items': 'चालान आइटम',
      'totalitems': 'कुल आइटम',
      'totalquantity': 'कुल मात्रा',
      'totalamount': 'कुल राशि',
      'refund': 'धनवापसी',
      'preparing_print': 'प्रिंट तैयार कर रहा है...',
      'printfailed': 'प्रिंट विफल',
      'no_sales_credits': 'कोई बिक्री क्रेडिट नहीं मिला',
      'no_matching_customers': 'कोई मिलान ग्राहक नहीं मिला',
      'total_sales_credit': 'कुल बिक्री क्रेडिट',
      'no_purchase_credits': 'कोई खरीद क्रेडिट नहीं मिला',
      'no_matching_purchase_credits': 'कोई मिलान खरीद क्रेडिट नहीं',
      'total_purchase_credit': 'कुल खरीद क्रेडिट',
      'unknown_supplier': 'अज्ञात आपूर्तिकर्ता',
      'purchase_credit_note': 'खरीद क्रेडिट नोट',
      'credit_note_not_found': 'क्रेडिट नोट नहीं मिला',
      'areyousure': 'क्या आप सुनिश्चित हैं?',
      'mode': 'मोड',
      'addnewcustomer': 'नया ग्राहक जोड़ें',
      'existing_customer': 'मौजूदा ग्राहक',
      'name_phone_required': 'कृपया नाम और फोन नंबर दर्ज करें',
      'no_customers_found': 'कोई ग्राहक नहीं मिला',
      'staffmanagement': 'कर्मचारी प्रबंधन',
      'addnewstaff': 'नया कर्मचारी जोड़ें',
      'savestaff': 'कर्मचारी सहेजें',
      'staff_added_success': 'कर्मचारी सफलतापूर्वक जोड़ा गया',
      'sale_return': 'बिक्री वापसी',
      'thismonth': 'इस महीने',
      'lastmonth': 'पिछले महीने',
      'invoicenumber': 'चालान नंबर',
      'customerdetails': 'ग्राहक विवरण',
      'cancel_bill': 'बिल रद्द करें',
      'enter_valid_amount': 'कृपया एक वैध राशि दर्ज करें',
      'payment_settled': 'भुगतान सफलतापूर्वक निपटाया गया',
      'payment_recorded': 'भुगतान दर्ज किया गया',
      'error_processing_payment': 'भुगतान प्रसंस्करण में त्रुटि',
      'add_discount': 'छूट जोड़ें',
      'enter_note': 'नोट दर्ज करें...',
      'bill_updated_success': 'बिल सफलतापूर्वक अपडेट किया गया',
      'error_updating_bill': 'बिल अपडेट करने में त्रुटि',

      // Reports page keys
      'analytics_overview': 'विश्लेषण और अवलोकन',
      'daybook_today': 'दिन पुस्तिका (आज)',
      'sales_transactions': 'बिक्री और लेनदेन',
      'item_sales_report': 'आइटम बिक्री रिपोर्ट',
      'inventory_products': 'इन्वेंटरी और उत्पाद',
      'low_stock_products': 'कम स्टॉक उत्पाद',
      'financials_tax': 'वित्त और टैक्स',
      'hsn_report': 'एचएसएन रिपोर्ट',
      'staff_sale_report': 'कर्मचारी बिक्री रिपोर्ट',
      'no_report_access': 'रिपोर्ट एक्सेस नहीं',
      'no_report_permission_msg': 'आपके पास किसी भी रिपोर्ट को देखने की अनुमति नहीं है। अपने व्यवस्थापक से संपर्क करें।',
      'hour': 'घंटा',
      'currency_symbol': '',

      // Expenses page keys
      'new_expense': 'नया खर्च',
      'expense_details': 'खर्च विवरण',
      'new_other_expense': 'नया अन्य खर्च',

      // Stock purchase keys
      'new_stock_purchase': 'नया स्टॉक खरीद',
      'purchase_details': 'खरीद विवरण',

      // Products page keys
      'filter_by_stock': 'स्टॉक द्वारा फ़िल्टर करें',
      'all_products': 'सभी उत्पाद',
      'low_stock_filter': 'कम स्टॉक (< 10)',
      'remove': 'हटाएं',
      'enter_valid_quantity': 'कृपया एक वैध मात्रा दर्ज करें',

      // Category keys
      'category_updated_success': 'श्रेणी सफलतापूर्वक अपडेट की गई',
      'category_deleted_success': 'श्रेणी सफलतापूर्वक हटाई गई',
      'are_you_sure_delete': 'क्या आप हटाना चाहते हैं',

      // AddProduct keys
      'add_new_unit': 'नई इकाई जोड़ें',

      // Profile/Settings keys
      'upgrade_plan': 'योजना अपग्रेड करें',
      'restricted_access': 'प्रतिबंधित पहुंच',

      // Bill keys
      'total_payable': 'कुल देय',
      'new_customer': 'नया ग्राहक',
      'select_customer': 'ग्राहक चुनें',
      'total_bill_amount': 'कुल बिल राशि',
      'paid_so_far': 'अब तक भुगतान किया गया',
      'total_bill': 'कुल बिल',

      // Quotation keys
      'share_error': 'साझा त्रुटि',
      'no_printer_selected': 'कोई प्रिंटर चयनित नहीं',
      'select_printer_from_settings': 'कृपया प्रिंट करने से पहले सेटिंग्स > प्रिंटर सेटअप से एक प्रिंटर चुनें।',
      'print_error': 'प्रिंट त्रुटि',

      // TaxSettings keys
      'create_type': 'प्रकार बनाएं',
      'add_tax_rate': 'टैक्स दर जोड़ें',
      'update_settings': 'सेटिंग्स अपडेट करें',

      // StaffManagement keys
      'no_staff_members': 'अभी तक कोई कर्मचारी सदस्य नहीं',
      'invite_to_start': 'शुरू करने के लिए किसी को आमंत्रित करें',
      'invite_new_staff': 'नए कर्मचारी को आमंत्रित करें',
      'send_invite': 'आमंत्रण भेजें',
      'edit_staff_member': 'कर्मचारी सदस्य संपादित करें',
      'remove_staff': 'कर्मचारी हटाएं',

      // QuotationsList keys
      'no_quotations_found': 'कोई कोटेशन नहीं मिला',
      'date_newest_first': 'तारीख: नवीनतम पहले',
      'date_oldest_first': 'तारीख: पुराना पहले',
      'amount_high_to_low': 'राशि: उच्च से निम्न',
      'amount_low_to_high': 'राशि: निम्न से उच्च',
      'settled': 'निपटाया गया',

      // Additional common keys
      'fill_required_fields': 'कृपया आवश्यक फ़ील्ड भरें',
      'expense_saved_success': 'खर्च सफलतापूर्वक सहेजा गया',
      'enter_category_name': 'कृपया श्रेणी नाम दर्ज करें',
      'category_added_success': 'श्रेणी सफलतापूर्वक जोड़ी गई',
      'category_exists': 'श्रेणी पहले से मौजूद है',

      // Saved ordekeys
      'order_deleted': 'ऑर्डर हटाया गया',
      'delete_order': 'ऑर्डर हटाएं',
      'no_saved_orders': 'कोई सहेजे गए ऑर्डर नहीं',

      // BusinessDetailsPage keys
      'complete_profile_title': 'अपना प्रोफ़ाइल पूरा करें',
      'complete_profile_subtitle': 'शुरू करने के लिए कृपया अपना व्यवसाय विवरण प्रदान करें',
      'personaldetails': 'व्यक्तिगत विवरण',
      'your_name': 'आपका नाम',
      'enter_full_name': 'अपना पूरा नाम दर्ज करें',
      'name_required': 'नाम आवश्यक है',
      'your_phone': 'आपका फोन नंबर',
      'phone_required': 'फोन आवश्यक है',
      'phone_invalid_10_digit': 'वैध 10-अंकीय फोन दर्ज करें',
      'businessdetails': 'व्यवसाय विवरण',
      'businessname': 'व्यवसाय नाम',
      'enter_business_name': 'अपना व्यवसाय नाम दर्ज करें',
      'business_name_required': 'व्यवसाय नाम आवश्यक है',
      'businessphone': 'व्यवसाय फोन नंबर',
      'enter_business_phone': 'व्यवसाय फोन नंबर दर्ज करें',
      'business_phone_required': 'व्यवसाय फोन आवश्यक है',
      'gstin_optional': 'जीएसटीआईएन (वैकल्पिक)',
      'enter_gstin': 'जीएसटीआईएन नंबर दर्ज करें',
      'businesslocation': 'व्यवसाय स्थान',
      'enter_business_location': 'अपना व्यवसाय स्थान दर्ज करें',
      'business_location_required': 'व्यवसाय स्थान आवश्यक है',
      'complete_registration': 'पंजीकरण पूरा करें',
      'business_registered_success': 'व्यवसाय सफलतापूर्वक पंजीकृत!',
      'failed_to_save': 'सहेजने में विफल',

      // SubscriptionPlanPage keys
      'subscription_expiry': 'समाप्ति',
      'permonth': '/माह',
      'six_months': '6 महीने',
      'peryear': '/वर्ष',
      'save_20': '20% बचाएं',
      'perperiod': '/अवधि',
      'full_feature_comparison': 'पूर्ण सुविधा तुलना',
      'freeplan': 'मुफ्त',
      'bulk_inventory': 'थोक इन्वेंटरी',
      'logo_on_bill': 'बिल पर लोगो',
      'customer_credit': 'ग्राहक क्रेडिट',
      'edit_bill': 'बिल संपादित करें',
      'taxreport': 'टैक्स रिपोर्ट',
      'import_contacts': 'संपर्क आयात करें',
      'pos_billing': 'पीओएस बिलिंग',
      'cloud_storage': 'क्लाउड स्टोरेज',
      'currentplan': 'वर्तमान योजना',
      'pay_now': 'अब भुगतान करें',
      'paymentsuccessful': 'भुगतान सफल! योजना अपग्रेड हो गई।',
      'paymentfailed': 'भुगतान विफल',

      // BarcodeScanner keys
      'scanbarcode': 'बारकोड स्कैन करें',
      'product_added_scanned': 'उत्पाद जोड़ा गया',
      'total_scanned': 'कुल स्कैन किया गया',
      'products_scanned': 'स्कैन किए गए उत्पाद',
      'scan_multiple_products': 'एकाधिक उत्पाद स्कैन करें\nपूरा होने पर वापस दबाएं',

      // Language settings keys
      'available_languages': 'उपलब्ध भाषाएं',
      'language_changed_to': 'भाषा बदली गई',
      'common_translations': 'सामान्य अनुवाद',

      // Additional keys
      'nodata': 'कोई डेटा उपलब्ध नहीं',
      'daybook': 'दिन पुस्तिका',
      'sales_summary': 'बिक्री सारांश',
      'customername': 'ग्राहक का नाम',
      'customerphone': 'ग्राहक फोन',

      // AddProduct page localization keys
      'item_information': 'आइटम जानकारी',
      'item_name': 'आइटम का नाम',
      'leave_blank_for_price': 'बिक्री के समय मूल्य के लिए खाली छोड़ें।',
      'more_details': 'अधिक विवरण',
      'cost_price_optional': 'लागत मूल्य (वैकल्पिक)',
      'mrp_optional': 'एमआरपी (वैकल्पिक)',
      'product_code': 'उत्पाद कोड',
      'generate': 'उत्पन्न करें',
      'find': 'खोजें',
      'hsn_scn': 'एचएसएन/एससीएन',
      'barcode_info': 'बाहरी बारकोड रीडर से बारकोड जोड़ने के लिए, बारकोड फ़ील्ड पर टैप करें और बारकोड स्कैन करें',
      'unit': 'इकाई',
      'stock_unit': 'स्टॉक इकाई',
      'this_field_is_required': 'यह फ़ील्ड आवश्यक है',

      // Category.dart specific keys
      'search_categories': 'श्रेणियाँ खोजें...',
      'no_categories_yet': 'अभी तक कोई श्रेणी नहीं',
      'add_first_category': 'उत्पादों को व्यवस्थित करने के लिए अपनी पहली श्रेणी जोड़ें',
      'no_categories_found': 'कोई श्रेणी नहीं मिली',
      'try_searching_keywords': 'विभिन्न कीवर्ड से खोजने का प्रयास करें',
      'add_product': 'उत्पाद जोड़ें',
      'create_new_product': 'नया उत्पाद बनाएं',
      'add_existing_product': 'मौजूदा उत्पाद जोड़ें',
      'no_products_available': 'कोई उत्पाद उपलब्ध नहीं',
      'current': 'वर्तमान',
      'price_on_sale': 'बिक्री पर मूल्य',
      'added_to': 'में जोड़ा गया',
    },

    'ta': {
      // Common
      'app_name': 'மேக்ஸ்பில்அப்',
      'welcome': 'வரவேற்கிறோம்',
      'save': 'சேமி',
      'cancel': 'ரத்து',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'add': 'சேர்',
      'update': 'புதுப்பி',
      'search': 'தேடு',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'ok': 'சரி',
      'done': 'முடிந்தது',
      'loading': 'ஏற்றுகிறது...',
      'coming_soon': 'விரைவில் வரும்',
      'used': 'பயன்படுத்தப்பட்டது',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'invoice': 'விலைப்பட்டியல்',

      // Navigation
      'home': 'முகப்பு',
      'sales': 'விற்பனை',
      'stocks': 'சரக்கு',
      'reports': 'அறிக்கைகள்',
      'menu': 'பட்டியல்',

      // Sales
      'new_sale': 'விற்பனை',
      'sale_all': 'அனைத்து விற்பனை',
      'quick_sale': 'விரைவு விற்பனை',
      'saved_orders': 'சேமிக்கப்பட்ட ஆர்டர்கள்',
      'save_order': 'ஆர்டர் சேமி',
      'complete_payment': 'கட்டணம் முடிக்கவும்',
      'add_to_cart': 'கார்ட்டில் சேர்',
      'cart': 'கார்ட்',
      'checkout': 'செக்அவுட்',
      'payment_mode': 'கட்டண முறை',
      'cash': 'பணம்',
      'online': 'ஆன்லைன்',
      'credit': 'கடன்',
      'split_payment': 'பிரிக்கப்பட்ட கட்டணம்',

      // Bill
      'subtotal': 'துணை மொத்தம்',
      'discount': 'தள்ளுபடி',
      'tax': 'வரி',
      'total': 'மொத்தம்',
      'grand_total': 'பெரும் மொத்தம்',
      'amount_received': 'பெறப்பட்ட தொகை',
      'change': 'மாற்றம்',
      'customer': 'வாடிக்கையாளர்',
      'add_customer': 'வாடிக்கையாளர் சேர்',

      // Products/Stocks
      'products': 'பொருட்கள்',
      'category': 'வகை',
      'addproduct': 'பொருள் சேர்',
      'price': 'விலை',
      'cost_price': 'செலவு விலை',
      'mrp': 'எம்பிபி',
      'quantity': 'அளவு',
      'barcode': 'பார்கோடு',
      'stock': 'சரக்கு',
      'in_stock': 'சரக்கில் உள்ளது',
      'out_of_stock': 'சரக்கு தீர்ந்தது',
      'low_stock': 'குறைந்த சரக்கு',

      // Tax
      'tax_settings': 'வரி அமைப்புகள்',
      'add_tax': 'வரி சேர்',
      'tax_name': 'வரி பெயர்',
      'tax_percentage': 'வரி %',
      'price_includes_tax': 'விலையில் வரி உள்ளது',
      'price_without_tax': 'வரி இல்லாத விலை',
      'zero_rated_tax': 'பூஜ்ஜிய வரி',
      'exempt_tax': 'வரி விலக்கு',

      // Settings
      'profile': 'சுயவிவரம்',
      'business_details': 'வணிக விவரங்கள்',
      'business_name': 'வணிக பெயர்',
      'business_phone': 'வணிக தொலைபேசி',
      'business_location': 'வணிக இடம்',
      'business_email': 'வணிக மின்னஞ்சல்',
      'gstin': 'ஜிஎஸ்டிஐஎன்',
      'choose_language': 'மொழியைத் தேர்ந்தெடு',
      'theme': 'தீம்',
      'printer_setup': 'அச்சுப்பொறி அமைப்பு',
      'receipt_customization': 'ரசீது தனிப்பயனாக்கம்',
      'feature_settings': 'அம்ச அமைப்புகள்',
      'help': 'உதவி',
      'about': 'பற்றி',

      // Reports
      'daily_report': 'தினசரி அறிக்கை',
      'monthly_report': 'மாதாந்திர அறிக்கை',
      'sales_report': 'விற்பனை அறிக்கை',
      'stock_report': 'சரக்கு அறிக்கை',
      'tax_report': 'வரி அறிக்கை',
      'profit_loss': 'இலாபம் மற்றும் நட்டம்',

      // Messages
      'product_added': 'பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது',
      'product_updated': 'பொருள் புதுப்பிக்கப்பட்டது',
      'product_deleted': 'பொருள் நீக்கப்பட்டது',
      'sale_completed': 'விற்பனை முடிந்தது',
      'payment_successful': 'கட்டணம் வெற்றி',
      'payment_failed': 'கட்டணம் தோல்வி',
      'no_items_in_cart': 'கார்ட்டில் பொருட்கள் இல்லை',
      'invalid_input': 'தவறான உள்ளீடு',
      'required_field': 'இந்த புலம் தேவை',
      'confirm_delete': 'நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
      'saved_offline': 'ஆஃப்லைனில் சேமிக்கப்பட்டது. ஆன்லைனில் ஒத்திசைக்கப்படும்.',
      'sync_completed': 'ஒத்திசைவு முடிந்தது',

      // Additional Pages
      'quotations': 'மேற்கோள்கள்',
      'create_quotation': 'மேற்கோள் உருவாக்கு',
      'quotation_list': 'மேற்கோள் பட்டியல்',
      'convert_to_sale': 'விற்பனையாக மாற்று',
      'expenses': 'செலவுகள்',
      'other_expenses': 'மற்ற செலவுகள்',
      'add_expense': 'செலவு சேர்',
      'expense_category': 'செலவு வகை',
      'categories': 'வகைகள்',
      'add_category': 'வகை சேர்',
      'staff_management': 'பணியாளர் மேலாண்மை',
      'add_staff': 'பணியாளர் சேர்',
      'customer_management': 'வாடிக்கையாளர் மேலாண்மை',
      'customers': 'வாடிக்கையாளர்கள்',
      'supplier': 'விநியோகஸ்தர்',
      'purchase': 'கொள்முதல்',
      'stock_purchase': 'சரக்கு கொள்முதல்',
      'view': 'காண்க',
      'print': 'அச்சிடு',
      'share': 'பகிர்',
      'receipt': 'ரசீது',
      'date': 'தேதி',
      'time': 'நேரம்',
      'from': 'இருந்து',
      'to': 'வரை',
      'all': 'அனைத்தும்',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'this_week': 'இந்த வாரம்',
      'this_month': 'இந்த மாதம்',
      'custom': 'தனிப்பயன்',
      'apply': 'பயன்படுத்து',
      'reset': 'மீட்டமை',
      'export': 'ஏற்றுமதி',
      'download': 'பதிவிறக்கு',
      'upload': 'பதிவேற்று',
      'back': 'பின்',
      'next': 'அடுத்து',
      'previous': 'முந்தைய',
      'finish': 'முடி',
      'skip': 'தவிர்',
      'continue': 'தொடர்',
      'close': 'மூடு',
      'open': 'திற',
      'refresh': 'புதுப்பி',
      'sync': 'ஒத்திசை',
      'online_mode': 'ஆன்லைன் முறை',
      'offline_mode': 'ஆஃப்லைன் முறை',
      'select': 'தேர்ந்தெடு',
      'select_all': 'அனைத்தையும் தேர்ந்தெடு',
      'deselect_all': 'அனைத்தையும் தேர்வு நீக்கு',
      'filter': 'வடிகட்டு',
      'sort': 'வரிசைப்படுத்து',
      'ascending': 'ஏறுவரிசை',
      'descending': 'இறங்குவரிசை',
      'name': 'பெயர்',
      'description': 'விளக்கம்',
      'amount': 'தொகை',
      'paid': 'செலுத்தப்பட்டது',
      'unpaid': 'செலுத்தப்படாதது',
      'pending': 'நிலுவையில்',
      'completed': 'முடிந்தது',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'active': 'செயல்படும்',
      'inactive': 'செயலற்றது',
      'enabled': 'இயக்கப்பட்டது',
      'disabled': 'முடக்கப்பட்டது',
      'phone': 'தொலைபேசி',
      'email': 'மின்னஞ்சல்',
      'address': 'முகவரி',
      'city': 'நகரம்',
      'state': 'மாநிலம்',
      'country': 'நாடு',
      'pincode': 'அஞ்சல் குறியீடு',
      'notes': 'குறிப்புகள்',
      'remarks': 'கருத்துகள்',
      'status': 'நிலை',
      'action': 'செயல்',
      'actions': 'செயல்கள்',
      'details': 'விவரங்கள்',
      'summary': 'சுருக்கம்',
      'billing': 'பில்லிங்',
      'shipping': 'அனுப்புதல்',
      'payment': 'கட்டணம்',
      'order': 'ஆர்டர்',
      'orders': 'ஆர்டர்கள்',
      'item': 'பொருள்',
      'items': 'பொருட்கள்',
      'unit': 'அலகு',
      'rate': 'விகிதம்',
      'gst': 'ஜிஎஸ்டி',
      'vat': 'வேட்',
      'cgst': 'சிஜிஎஸ்டி',
      'sgst': 'எஸ்ஜிஎஸ்டி',
      'igst': 'ஐஜிஎஸ்டி',
      'total_items': 'மொத்த பொருட்கள்',
      'total_amount': 'மொத்த தொகை',
      'due_amount': 'நிலுவை தொகை',
      'balance': 'இருப்பு',
      'credit_limit': 'கடன் வரம்பு',
      'available': 'கிடைக்கிறது',
      'unavailable': 'கிடைக்கவில்லை',

      // Additional UI strings
      'bill_history': 'பில் வரலாறு',
      'bill_summary': 'பில் சுருக்கம்',
      'bill_to': 'பில் செலுத்துபவர்',
      'bill_cancelled': 'பில் ரத்து',
      'bill_description': 'பில் விளக்கம்',
      'clear': 'அழி',
      'clear_order': 'ஆர்டர் அழி',
      'clear_all': 'அனைத்தையும் அழி',
      'report': 'அறிக்கை',
      'no_products_found': 'பொருட்கள் எதுவும் இல்லை',
      'product_not_found': 'பொருள் கிடைக்கவில்லை',
      'max_stock_reached': 'அதிகபட்ச சரக்கு எட்டப்பட்டது! ({0} உள்ளது)',
      'enter_quantity': 'அளவை உள்ளிடவும்',
      'saved': 'சேமிக்கப்பட்டது',
      'quotation': 'மேற்கோள்',
      'credit_notes': 'கிரெடிட் நோட்டுகள்',
      'add_credit_note': 'கிரெடிட் நோட் சேர்',
      'credit_details': 'கிரெடிட் விவரங்கள்',
      'available_credit_notes': 'கிடைக்கும் கிரெடிட் நோட்டுகள்',
      'bill_wise': 'பில் வைஸ்',
      'customer_details': 'வாடிக்கையாளர் விவரங்கள்',
      'add_customer_details': 'வாடிக்கையாளர் விவரங்களை சேர்',
      'add_new_customer': 'புதிய வாடிக்கையாளரை சேர்',
      'customer_name': 'வாடிக்கையாளர் பெயர்',
      'customer_phone': 'வாடிக்கையாளர் தொலைபேசி',
      'payment_method': 'கட்டண முறை',
      'cash_payment': 'பணம் கட்டணம்',
      'online_payment': 'ஆன்லைன் கட்டணம்',
      'credit_payment': 'கடன் கட்டணம்',
      'split': 'பிரி',
      'received': 'பெறப்பட்டது',
      'due': 'நிலுவை',
      'advance': 'முன்பணம்',
      'internal_note': 'உள் குறிப்பு',
      'add_internal_note': 'உள் குறிப்பு சேர்',
      'add_note': 'குறிப்பு சேர்',
      'discount_percent': 'தள்ளுபடி (%)',
      'discount_amount': 'தள்ளுபடி தொகை',
      'price_with_tax': 'வரி உடன் விலை',
      'tax_amount': 'வரி தொகை',
      'payment_details': 'கட்டண விவரங்கள்',
      'billing_details': 'பில்லிங் விவரங்கள்',
      'proceed': 'முன்னேறு',
      'discard': 'தவிர்',
      'confirm': 'உறுதி செய்',
      'warning': 'எச்சரிக்கை',
      'are_you_sure': 'நிச்சயமாக உள்ளீர்களா?',
      'cannot_be_undone': 'இந்த செயலை மீளமைக்க முடியாது',
      'discard_bill': 'பில் தவிர்',
      'are_you_sure_discard': 'இந்த பிலை தவிர்க்க விரும்புகிறீர்களா?',
      'delete_product': 'பொருளை நீக்கு',
      'are_you_sure_delete_product': 'இந்த பொருளை நீக்க விரும்புகிறீர்களா?',
      'item_name': 'பொருள் பெயர்',
      'hsn_code': 'எசெஸ்என் குறியீடு',
      'unit_price': 'அலகு விலை',
      'selling_price': 'விற்பனை விலை',
      'stock_enabled': 'சரக்கு இயக்கப்பட்டது',
      'current_stock': 'தற்போதைய சரக்கு',
      'low_stock_alert': 'குறைந்த சரக்கு எச்சரிக்கை',
      'min_stock': 'குறைந்தபட்ச சரக்கு',
      'max_stock': 'அதிகபட்ச சரக்கு',
      'reorder_level': 'மீண்டும் ஆர்டர் நிலை',
      'category_name': 'வகை பெயர்',
      'add_category_name': 'வகை பெயரை சேர்',
      'delete_category': 'வகையை நீக்கு',
      'are_you_sure_delete_category': 'இந்த வகையை நீக்க விரும்புகிறீர்களா?',
      'edit_product': 'பொருளை திருத்து',
      'edit_category': 'வகையை திருத்து',
      'save_product': 'பொருளை சேமி',
      'save_category': 'வகையை சேமி',
      'required': 'தேவை',
      'invalid': 'தவறானது',
      'enter_valid_value': 'சரியான மதிப்பை உள்ளிடவும்',
      'expense_name': 'செலவு பெயர்',
      'expense_amount': 'செலவு தொகை',
      'expense_date': 'செலவு தேதி',
      'expense_type': 'செலவு வகை',
      'add_expense_category': 'செலவு வகையை சேர்',
      'expense_categories': 'செலவு வகைகள்',
      'staff_name': 'பணியாளர் பெயர்',
      'staff_phone': 'பணியாளர் தொலைபேசி',
      'staff_email': 'பணியாளர் மின்னஞ்சல்',
      'staff_role': 'பணியாளர் பங்கு',
      'permissions': 'அனுமதிகள்',
      'grant_permissions': 'அனுமதிகள் வழங்கு',
      'role': 'பங்கு',
      'admin': 'நிர்வாகி',
      'staff': 'பணியாளர்',
      'cashier': 'காசியர்',
      'manager': 'மேலாளர்',
      'add_new_staff': 'புதிய பணியாளரை சேர்',
      'edit_staff': 'பணியாளரை திருத்து',
      'delete_staff': 'பணியாளரை நீக்கு',
      'are_you_sure_delete_staff': 'இந்த பணியாளரை நீக்க விரும்புகிறீர்களா?',
      'login': 'உள்நுழைவு',
      'email_phone': 'மின்னஞ்சல் / தொலைபேசி',
      'password': 'கடவுச்சொல்',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டீர்களா',
      'sign_in': 'உள்நுழைக',
      'sign_up': 'பதிவு செய்ய',
      'sign_in_with_google': 'கூகிள் மூலம் உள்நுழைக',
      'create_account': 'கணக்கை உருவாக்கு',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'enter_email': 'மின்னஞ்சலை உள்ளிடவும்',
      'enter_phone': 'தொலைபேசியை உள்ளிடவும்',
      'enter_password': 'கடவுச்சொல்லை உள்ளிடவும்',
      'invalid_email': 'தவறான மின்னஞ்சல்',
      'invalid_phone': 'தவறான தொலைபேசி',
      'password_too_short': 'கடவுச்சொல் மிகவும் குறுகியது',
      'login_failed': 'உள்நுழைவு தோல்வி',
      'signup_failed': 'பதிவு தோல்வி',
      'logout_confirm': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'verify_email': 'மின்னஞ்சல் சரிபார்க்கவும்',
      'verify_email_message': 'தொடர உங்கள் இன்பாக்ஸை சரிபார்த்து உங்கள் மின்னஞ்சல் முகவரியை சரிபார்க்கவும்.',
      'resend_email': 'மின்னஞ்சலை மீண்டும் அனுப்பவும்',
      'verification_email_sent': 'சரிபார்ப்பு மின்னஞ்சல் அனுப்பப்பட்டது!',
      'approval_pending': 'ஒப்புதல் நிலுவையில்',
      'admin_approval': 'உங்கள் மின்னஞ்சல் சரிபார்க்கப்பட்டது! ஆனால், உங்கள் கணக்கு நிர்வாக ஒப்புதலுக்காக காத்திருக்கிறது. தயவு செய்து உங்கள் கடை நிர்வாகியை உங்கள் கணக்கை ஒப்புதல் செய்ய கேளுங்கள்.',
      'google_sign_in_error': 'கூகிள் உள்நுழைவு பிழை',
      'reset_link_sent': 'மீட்டமை இணைப்பு அனுப்பப்பட்டது!',
      'error_sending_reset': 'மீட்டமை இணைப்பை அனுப்புவதில் பிழை',
      'enter_email_reset': 'கடவுச்சொல்லை மீட்டமைக்க மின்னஞ்சலை உள்ளிடவும்',
      'account_does_not_exist': 'கணக்கு இல்லை.',
      'incorrect_password': 'தவறான கடவுச்சொல்.',
      'welcome_to': 'வரவேற்கிறோம்',
      'login_staff': 'உள்நுழைவு (பணியாளர்)',
      'by_proceeding_agree': 'தொடர்வதன் மூலம், நீங்கள் எங்கள் ',
      'terms_and_conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'refund_and_cancellation_policy': 'பணத்தைத் திரும்பப்பெறும் மற்றும் ரத்து கொள்கை',
      'subscription_plan': 'சந்தா திட்டம்',
      'choose_plan': 'திட்டத்தை தேர்ந்தெடு',
      'current_plan': 'தற்போதைய திட்டம்',
      'free_plan': 'இலவச திட்டம்',
      'basic_plan': 'அடிப்படை திட்டம்',
      'premium_plan': 'பிரீமியம் திட்டம்',
      'enterprise_plan': 'நிறுவன திட்டம்',
      'upgrade': 'மேம்படுத்து',
      'upgrade_now': 'இப்போது மேம்படுத்து',
      'upgrade_to_premium': 'பிரீமியம் அளவிற்கு மேம்படுத்து',
      'features': 'அம்சங்கள்',
      'per_month': 'மாதத்திற்கு',
      'per_year': 'வருடத்திற்கு',
      'best_value': 'சிறந்த மதிப்பு',
      'most_popular': 'மிகவும் பிரபலமானது',
      'contact_us': 'எங்களை தொடர்பு கொள்ளவும்',
      'terms_conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'privacy_policy': 'தனியுரிமை கொள்கை',
      'version': 'பதிப்பு',
      'build': 'கட்டமைப்பு',
      'developed_by': 'உருவாக்கப்பட்டது',
      'powered_by': 'சக்தி வழங்கப்பட்டது',
      'all_rights_reserved': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டுள்ளன',
      'language': 'மொழி',
      'currency': 'நாணயம்',
      'timezone': 'நேர மண்டலம்',
      'notifications': 'அறிவிப்புகள்',
      'enable_notifications': 'அறிவிப்புகளை இயக்கு',
      'sound': 'ஒலி',
      'vibration': 'அதிர்வு',
      'backup': 'காப்பு',
      'restore': 'மீட்டமை',
      'backup_restore': 'காப்பு மற்றும் மீட்டமை',
      'create_backup': 'காப்பு உருவாக்கு',
      'restore_backup': 'காப்பை மீட்டமை',
      'last_backup': 'கடைசி காப்பு',
      'no_backup': 'காப்பு இல்லை',
      'backup_success': 'காப்பு வெற்றி',
      'restore_success': 'மீட்டமைப்பு வெற்றி',
      'backup_failed': 'காப்பு தோல்வி',
      'restore_failed': 'மீட்டமைப்பு தோல்வி',
      'analytics': 'பகுப்பாய்வு',
      'dashboard': 'டாஷ்போர்டு',
      'overview': 'கண்ணோட்டம்',
      'statistics': 'புள்ளிவிவரங்கள்',
      'charts': 'விளக்கப்படங்கள்',
      'graphs': 'வரைபடங்கள்',
      'top_products': 'சிறந்த பொருட்கள்',
      'top_customers': 'சிறந்த வாடிக்கையாளர்கள்',
      'top_categories': 'சிறந்த வகைகள்',
      'recent_sales': 'சமீபத்திய விற்பனைகள்',
      'recent_orders': 'சமீபத்திய ஆர்டர்கள்',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'completed_orders': 'முடிக்கப்பட்ட ஆர்டர்கள்',
      'cancelled_orders': 'ரத்து செய்யப்பட்ட ஆர்டர்கள்',
      'total_sales': 'மொத்த விற்பனை',
      'total_revenue': 'மொத்த வருவாய்',
      'total_profit': 'மொத்த லாபம்',
      'total_orders': 'மொத்த ஆர்டர்கள்',
      'total_customers': 'மொத்த வாடிக்கையாளர்கள்',
      'total_products': 'மொத்த பொருட்கள்',
      'income': 'வருமானம்',
      'expense': 'செலவு',
      'profit': 'லாபம்',
      'loss': 'நட்டம்',
      'revenue': 'வருவாய்',
      'MAX Plus': 'வளர்ச்சி',
      'decline': 'சரிவு',
      'percentage': 'சதவீதம்',
      'change_from_last_month': 'கடந்த மாதத்திலிருந்து மாற்றம்',
      'change_from_last_week': 'கடந்த வாரத்திலிருந்து மாற்றம்',
      'last_7_days': 'கடந்த 7 நாட்கள்',
      'last_30_days': 'கடந்த 30 நாட்கள்',
      'last_90_days': 'கடந்த 90 நாட்கள்',
      'this_year': 'இந்த ஆண்டு',
      'last_year': 'கடந்த ஆண்டு',
      'custom_range': 'தனிப்பயன் வரம்பு',
      'start_date': 'தொடக்க தேதி',
      'end_date': 'முடிவு தேதி',
      'generate_report': 'அறிக்கையை உருவாக்கு',
      'download_report': 'அறிக்கையை பதிவிறக்கு',
      'print_report': 'அறிக்கையை அச்சிடு',
      'share_report': 'அறிக்கையை பகிர்',
      'email_report': 'அறிக்கையை மின்னஞ்சல் செய்',
      'pdf_report': 'பிஃப்டி அறிக்கை',
      'excel_report': 'எக்சல் அறிக்கை',
      'report_generated': 'அறிக்கை வெற்றிகரமாக உருவாக்கப்பட்டது',
      'report_failed': 'அறிக்கை உருவாக்குதல் தோல்வி',
      'no_data': 'தரவு இல்லை',
      'no_results': 'முடிவுகள் எதுவும் இல்லை',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      'reload': 'மீண்டும் ஏற்றவும்',
      'something_went_wrong': 'ஏதோ தவறு நடந்தது',
      'network_error': 'நெட்வொர்க் பிழை',
      'server_error': 'சர்வர் பிழை',
      'connection_failed': 'இணைப்பு தோல்வி',
      'please_check_internet': 'உங்கள் இணைய இணைப்பை சரிபார்க்கவும்',
      'offline': 'ஆஃப்லைன்',
      'connecting': 'இணைக்கிறது...',
      'syncing': 'ஒத்திசைக்கிறது...',
      'sync_failed': 'ஒத்திசைவு தோல்வி',
      'sync_success': 'வெற்றிகரமாக ஒத்திசைக்கப்பட்டது',
      'last_synced': 'கடைசி ஒத்திசைவு',
      'never_synced': 'எப்போதும் ஒத்திசைக்கப்படவில்லை',
      'sync_now': 'இப்போது ஒத்திசை',
      'auto_sync': 'தானியங்கி ஒத்திசைவு',
      'manual_sync': 'கைமுறை ஒத்திசைவு',
      'sync_settings': 'ஒத்திசைவு அமைப்புகள்',
      'data_usage': 'தரவு பயன்பாடு',
      'storage': 'சேமிப்பு',
      'clear_cache': 'கேஷ் அழி',
      'clear_data': 'தரவை அழி',
      'cache_cleared': 'கேஷ் அழிக்கப்பட்டது',
      'data_cleared': 'தரவு அழிக்கப்பட்டது',
      'confirm_clear': 'நிச்சயமாக அழிக்க விரும்புகிறீர்களா?',
      'scanning': 'ஸ்கேன் செய்யப்படுகிறது...',
      'scan_barcode': 'பார்கோடு ஸ்கேன்',
      'scan_qr': 'க்யூஆர் கோடு ஸ்கேன்',
      'camera_permission': 'கேமரா அனுமதி',
      'camera_permission_required': 'கேமரா அனுமதி தேவை',
      'grant_permission': 'அனுமதி வழங்கு',
      'permission_denied': 'அனுமதி மறுக்கப்பட்டது',
      'enable_from_settings': 'அமைப்புகளில் இருந்து இயக்கு',
      'printer_not_found': 'அச்சுப்பொறி கிடைக்கவில்லை',
      'printer_connected': 'அச்சுப்பொறி இணைக்கப்பட்டது',
      'printer_disconnected': 'அச்சுப்பொறி துண்டிக்கப்பட்டது',
      'connecting_printer': 'அச்சுப்பொறியை இணைக்கிறது...',
      'print_settings': 'அச்சு அமைப்புகள்',
      'paper_size': 'காகித அளவு',
      'print_quality': 'அச்சு தரம்',
      'copies': 'நகல்கள்',
      'print_preview': 'அச்சு முன்னோட்டம்',
      'printing': 'அச்சிடுகிறது...',
      'print_success': 'வெற்றிகரமாக அச்சிடப்பட்டது',
      'print_failed': 'அச்சிடுதல் தோல்வி',
      'bluetooth': 'ப்ளூடூத்',
      'wifi': 'வைஃபை',
      'usb': 'யூஎஸ்பி',
      'network': 'நெட்வொர்க்',
      'select_printer': 'அச்சுப்பொறியைத் தேர்ந்தெடு',
      'add_printer': 'அச்சுப்பொறியைச் சேர்',
      'remove_printer': 'அச்சுப்பொறியை நீக்கு',
      'test_print': 'சோதனை அச்சு',
      'invoice_number': 'விலைப்பட்டியல் எண்',
      'bill_number': 'பில் எண்',
      'order_number': 'ஆர்டர் எண்',
      'reference_number': 'குறிப்பு எண்',
      'transaction_id': 'பரிவர்த்தனை ஐடி',
      'payment_id': 'கட்டண ஐடி',
      'receipt_number': 'ரசீது எண்',
      'customer_copy': 'வாடிக்கையாளர் நகல்',
      'merchant_copy': 'வணிகர் நகல்',
      'thank_you': 'நன்றி',
      'visit_again': 'மீண்டும் வருக',
      'terms': 'விதிமுறைகள்',
      'signature': 'கையொப்பம்',
      'authorized_signature': 'அங்கீகரிக்கப்பட்ட கையொப்பம்',
      'stamp': 'முத்திரை',
      'company_stamp': 'நிறுவன முத்திரை',
      'powered_by_maxbillup': 'மேக்ஸ்பில்அப் மூலம் இயக்கப்படுகிறது',
      'generated_by': 'உருவாக்கப்பட்டது',
      'page': 'பக்கம்',
      'of': 'இன்',
      'sub_total': 'துணை மொத்தம்',
      'taxable_amount': 'வரி விதிக்கக்கூடிய தொகை',
      'tax_details': 'வரி விவரங்கள்',
      'round_off': 'சுற்று',
      'net_amount': 'நிகர தொகை',
      'amount_in_words': 'சொற்களில் தொகை',
      'rupees': 'ரூபாய்',
      'only': 'மட்டும்',
      'payment_status': 'கட்டண நிலை',
      'paid_amount': 'செலுத்தப்பட்ட தொகை',
      'remaining_amount': 'மீதமுள்ள தொகை',
      'change_return': 'மாற்றம் திரும்ப',
      'no_change': 'மாற்றம் இல்லை',
      'payment_type': 'கட்டண வகை',
      'card': 'கார்டு',
      'upi': 'யுபிஐ',
      'wallet': 'வாலெட்',
      'cheque': 'செக்',
      'bank_transfer': 'வங்கி பரிமாற்றம்',
      'other': 'மற்றவை',
      'specify': 'குறிப்பிடவும்',

      // Menu.dart specific keys
      'billhistory': 'பில் வரலாறு',
      'creditdetails': 'கிரெடிட் விவரங்கள்',
      'expense_report': 'செலவு அறிக்கை',
      'nobillsfound': 'பில்கள் எதுவும் இல்லை',
      'settle_bill': 'பில் தீர்க்கவும்',
      'by': 'மூலம்',
      'bill_not_found': 'பில் கிடைக்கவில்லை அல்லது நீக்கப்பட்டது.',
      'created_by': 'உருவாக்கியவர்',
      'issued_on': 'வழங்கப்பட்ட தேதி',
      'invoice_items': 'விலைப்பட்டியல் பொருட்கள்',
      'totalitems': 'மொத்த பொருட்கள்',
      'totalquantity': 'மொத்த அளவு',
      'totalamount': 'மொத்த தொகை',
      'refund': 'பணத்தைத் திரும்பப்பெறுதல்',
      'preparing_print': 'அச்சு தயாராக்கப்படுகிறது...',
      'printfailed': 'அச்சிடுதல் தோல்வி',
      'no_sales_credits': 'விற்பனை கிரெடிட்கள் எதுவும் இல்லை',
      'no_matching_customers': 'பொருந்தக்கூடிய வாடிக்கையாளர்கள் எதுவும் இல்லை',
      'total_sales_credit': 'மொத்த விற்பனை கிரெடிட்',
      'no_purchase_credits': 'கொள்முதல் கிரெடிட்கள் எதுவும் இல்லை',
      'no_matching_purchase_credits': 'பொருந்தக்கூடிய கொள்முதல் கிரெடிட்கள் இல்லை',
      'total_purchase_credit': 'மொத்த கொள்முதல் கிரெடிட்',
      'unknown_supplier': 'அறியப்படாத விநியோகஸ்தர்',
      'purchase_credit_note': 'கொள்முதல் கிரெடிட் நோட்',
      'credit_note_not_found': 'கிரெடிட் நோட் கிடைக்கவில்லை',
      'areyousure': 'நிச்சயமாக உள்ளீர்களா?',
      'mode': 'முறை',
      'addnewcustomer': 'புதிய வாடிக்கையாளரை சேர்',
      'existing_customer': 'ஏற்கனவே உள்ள வாடிக்கையாளர்',
      'name_phone_required': 'பெயர் மற்றும் தொலைபேசி எண்ணை உள்ளிடவும்',
      'no_customers_found': 'வாடிக்கையாளர்கள் எதுவும் இல்லை',
      'staffmanagement': 'பணியாளர் மேலாண்மை',
      'addnewstaff': 'புதிய பணியாளரை சேர்',
      'savestaff': 'பணியாளரை சேமி',
      'staff_added_success': 'பணியாளர் வெற்றிகரமாக சேர்க்கப்பட்டது',
      'sale_return': 'விற்பனை திரும்ப',
      'thismonth': 'இந்த மாதம்',
      'lastmonth': 'கடந்த மாதம்',
      'invoicenumber': 'விலைப்பட்டியல் எண்',
      'customerdetails': 'வாடிக்கையாளர் விவரங்கள்',
      'cancel_bill': 'பில் ரத்து செய்',
      'enter_valid_amount': 'சரியான தொகையை உள்ளிடவும்',
      'payment_settled': 'கட்டணம் வெற்றிகரமாக தீர்க்கப்பட்டது',
      'payment_recorded': 'கட்டணம் பதிவு செய்யப்பட்டது',
      'error_processing_payment': 'கட்டணம் செயல்படுத்துவதில் பிழை',
      'add_discount': 'தள்ளுபடி சேர்',
      'enter_note': 'குறிப்பை உள்ளிடவும்...',
      'bill_updated_success': 'பில் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'error_updating_bill': 'பில் புதுப்பிப்பதில் பிழை',

      // Reports page keys
      'analytics_overview': 'பகுப்பாய்வு மற்றும் கண்ணோட்டம்',
      'daybook_today': 'தினசரி புத்தகம் (இன்று)',
      'sales_transactions': 'விற்பனை மற்றும் பரிவர்த்தனைகள்',
      'item_sales_report': 'பொருள் விற்பனை அறிக்கை',
      'inventory_products': 'சரக்கு மற்றும் பொருட்கள்',
      'low_stock_products': 'குறைந்த சரக்கு பொருட்கள்',
      'financials_tax': 'நிதி மற்றும் வரி',
      'hsn_report': 'எசெஸ்என் அறிக்கை',
      'staff_sale_report': 'பணியாளர் விற்பனை அறிக்கை',
      'no_report_access': 'அறிக்கை அணுகல் இல்லை',
      'no_report_permission_msg': 'எந்த அறிக்கையையும் பார்க்க உங்களுக்கு அனுமதி இல்லை. உங்கள் நிர்வாகியை தொடர்பு கொள்ளவும்.',
      'hour': 'மணி',
      'currency_symbol': '',

      // Expenses page keys
      'new_expense': 'புதிய செலவு',
      'expense_details': 'செலவு விவரங்கள்',
      'new_other_expense': 'புதிய மற்ற செலவு',

      // Stock purchase keys
      'new_stock_purchase': 'புதிய சரக்கு கொள்முதல்',
      'purchase_details': 'கொள்முதல் விவரங்கள்',

      // Products page keys
      'filter_by_stock': 'சரக்கு மூலம் வடிகட்டு',
      'all_products': 'அனைத்து பொருட்கள்',
      'low_stock_filter': 'குறைந்த சரக்கு (< 10)',
      'remove': 'அகற்று',
      'enter_valid_quantity': 'சரியான அளவை உள்ளிடவும்',

      // Category keys
      'category_updated_success': 'வகை வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'category_deleted_success': 'வகை வெற்றிகரமாக நீக்கப்பட்டது',
      'are_you_sure_delete': 'நிச்சயமாக நீக்க விரும்புகிறீர்களா',

      // AddProduct keys
      'add_new_unit': 'புதிய அலகு சேர்',

      // Profile/Settings keys
      'upgrade_plan': 'திட்டத்தை மேம்படுத்து',
      'restricted_access': 'கட்டுப்படுத்தப்பட்ட அணுகல்',

      // Bill keys
      'total_payable': 'மொத்த செலுத்த வேண்டியது',
      'new_customer': 'புதிய வாடிக்கையாளர்',
      'select_customer': 'வாடிக்கையாளரைத் தேர்ந்தெடு',
      'total_bill_amount': 'மொத்த பில் தொகை',
      'paid_so_far': 'இதுவரை செலுத்தப்பட்டது',
      'total_bill': 'மொத்த பில்',

      // Quotation keys
      'share_error': 'பகிர்வு பிழை',
      'no_printer_selected': 'அச்சுப்பொறி தேர்ந்தெடுக்கப்படவில்லை',
      'select_printer_from_settings': 'அச்சிடுவதற்கு முன் அமைப்புகள் > அச்சுப்பொறி அமைப்பில் இருந்து ஒரு அச்சுப்பொறியை தேர்ந்தெடுக்கவும்.',
      'print_error': 'அச்சு பிழை',

      // TaxSettings keys
      'create_type': 'வகையை உருவாக்கு',
      'add_tax_rate': 'வரி விகிதம் சேர்',
      'update_settings': 'அமைப்புகளை புதுப்பி',

      // StaffManagement keys
      'no_staff_members': 'இதுவரை பணியாளர் உறுப்பினர்கள் இல்லை',
      'invite_to_start': 'தொடங்க ஒருவரை அழைக்கவும்',
      'invite_new_staff': 'புதிய பணியாளரை அழை',
      'send_invite': 'அழைப்பு அனுப்பு',
      'edit_staff_member': 'பணியாளர் உறுப்பினரை திருத்து',
      'remove_staff': 'பணியாளரை அகற்று',

      // QuotationsList keys
      'no_quotations_found': 'மேற்கோள்கள் எதுவும் இல்லை',
      'date_newest_first': 'தேதி: புதியது முதலில்',
      'date_oldest_first': 'தேதி: பழையது முதலில்',
      'amount_high_to_low': 'தொகை: உயர்ந்ததிலிருந்து குறைந்தது',
      'amount_low_to_high': 'தொகை: குறைந்ததிலிருந்து உயர்ந்தது',
      'settled': 'தீர்க்கப்பட்டது',

      // Additional common keys
      'fill_required_fields': 'தேவையான புலங்களை நிரப்பவும்',
      'expense_saved_success': 'செலவு வெற்றிகரமாக சேமிக்கப்பட்டது',
      'enter_category_name': 'வகை பெயரை உள்ளிடவும்',
      'category_added_success': 'வகை வெற்றிகரமாக சேர்க்கப்பட்டது',
      'category_exists': 'வகை ஏற்கனவே உள்ளது',

      // Saved ordekeys
      'order_deleted': 'ஆர்டர் நீக்கப்பட்டது',
      'delete_order': 'ஆர்டரை நீக்கு',
      'no_saved_orders': 'சேமிக்கப்பட்ட ஆர்டர்கள் இல்லை',

      // BusinessDetailsPage keys
      'complete_profile_title': 'உங்கள் சுயவிவரத்தை முடிக்கவும்',
      'complete_profile_subtitle': 'தொடங்க உங்கள் வணிக விவரங்களை வழங்கவும்',
      'personaldetails': 'தனிப்பட்ட விவரங்கள்',
      'your_name': 'உங்கள் பெயர்',
      'enter_full_name': 'உங்கள் முழு பெயரை உள்ளிடவும்',
      'name_required': 'பெயர் தேவை',
      'your_phone': 'உங்கள் தொலைபேசி எண்',
      'phone_required': 'தொலைபேசி தேவை',
      'phone_invalid_10_digit': 'சரியான 10-இலக்க தொலைபேசியை உள்ளிடவும்',
      'businessdetails': 'வணிக விவரங்கள்',
      'businessname': 'வணிக பெயர்',
      'enter_business_name': 'உங்கள் வணிக பெயரை உள்ளிடவும்',
      'business_name_required': 'வணிக பெயர் தேவை',
      'businessphone': 'வணிக தொலைபேசி எண்',
      'enter_business_phone': 'வணிக தொலைபேசி எண்ணை உள்ளிடவும்',
      'business_phone_required': 'வணிக தொலைபேசி தேவை',
      'gstin_optional': 'ஜிஎஸ்டிஐஎன் (விருப்பத்தேர்வு)',
      'enter_gstin': 'ஜிஎஸ்டிஐஎன் எண்ணை உள்ளிடவும்',
      'businesslocation': 'வணிக இடம்',
      'enter_business_location': 'உங்கள் வணிக இடத்தை உள்ளிடவும்',
      'business_location_required': 'வணிக இடம் தேவை',
      'complete_registration': 'பதிவை முடிக்கவும்',
      'business_registered_success': 'வணிகம் வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
      'failed_to_save': 'சேமிக்க முடியவில்லை',

      // SubscriptionPlanPage keys
      'subscription_expiry': 'காலாவதி',
      'permonth': '/மாதம்',
      'six_months': '6 மாதங்கள்',
      'peryear': '/வருடம்',
      'save_20': '20% சேமி',
      'perperiod': '/காலம்',
      'full_feature_comparison': 'முழு அம்ச ஒப்பீடு',
      'freeplan': 'இலவசம்',
      'bulk_inventory': 'மொத்த சரக்கு',
      'logo_on_bill': 'பில்லில் லோகோ',
      'customer_credit': 'வாடிக்கையாளர் கடன்',
      'edit_bill': 'பில் திருத்து',
      'taxreport': 'வரி அறிக்கை',
      'import_contacts': 'தொடர்புகளை இறக்கு',
      'pos_billing': 'பிஓஎஸ் பில்லிங்',
      'cloud_storage': 'கிளவுட் சேமிப்பு',
      'currentplan': 'தற்போதைய திட்டம்',
      'pay_now': 'இப்போது செலுத்து',
      'paymentsuccessful': 'கட்டணம் வெற்றி! திட்டம் மேம்படுத்தப்பட்டது.',
      'paymentfailed': 'கட்டணம் தோல்வி',

      // BarcodeScanner keys
      'scanbarcode': 'பார்கோடு ஸ்கேன்',
      'product_added_scanned': 'பொருள் சேர்க்கப்பட்டது',
      'total_scanned': 'மொத்தம் ஸ்கேன் செய்யப்பட்டது',
      'products_scanned': 'ஸ்கேன் செய்யப்பட்ட பொருட்கள்',
      'scan_multiple_products': 'பல பொருட்களை ஸ்கேன் செய்யவும்\nமுடிந்ததும் பின் செல்லவும்',

      // Language settings keys
      'available_languages': 'கிடைக்கும் மொழிகள்',
      'language_changed_to': 'மொழி மாற்றப்பட்டது',
      'common_translations': 'பொதுவான மொழிபெயர்ப்புகள்',

      // Additional keys
      'nodata': 'தரவு இல்லை',
      'daybook': 'தினசரி புத்தகம்',
      'sales_summary': 'விற்பனை சுருக்கம்',
      'customername': 'வாடிக்கையாளர் பெயர்',
      'customerphone': 'வாடிக்கையாளர் தொலைபேசி',

      // AddProduct page localization keys
      'item_information': 'பொருள் தகவல்',
      'item_name': 'பொருள் பெயர்',
      'leave_blank_for_price': 'விற்பனை நேரத்தில் விலைக்கு காலியாக விடவும்.',
      'more_details': 'மேலும் விவரங்கள்',
      'cost_price_optional': 'செலவு விலை (விருப்பத்தேர்வு)',
      'mrp_optional': 'எம்பிபி (விருப்பத்தேர்வு)',
      'product_code': 'பொருள் குறியீடு',
      'generate': 'உருவாக்கு',
      'find': 'கண்டுபிடி',
      'hsn_scn': 'எசெஸ்என்/எஸ்சிஎன்',
      'barcode_info': 'வெளிப்புற பார்கோடு வாசிப்பாளரில் இருந்து பார்கோடு சேர்க்க, பார்கோடு புலத்தை தட்டவும் மற்றும் பார்கோடு ஸ்கேன் செய்யவும்',
      'unit': 'அலகு',
      'stock_unit': 'சரக்கு அலகு',
      'this_field_is_required': 'இந்த புலம் தேவை',

      // Category.dart specific keys
      'search_categories': 'வகைகளை தேடு...',
      'no_categories_yet': 'இன்னும் வகைகள் இல்லை',
      'add_first_category': 'பொருட்களை ஒழுங்குபடுத்த உங்கள் முதல் வகையை சேர்க்கவும்',
      'no_categories_found': 'வகைகள் எதுவும் இல்லை',
      'try_searching_keywords': 'வேறு வார்த்தைகளுடன் தேட முயற்சிக்கவும்',
      'add_product': 'பொருள் சேர்',
      'create_new_product': 'புதிய பொருள் உருவாக்கு',
      'add_existing_product': 'ஏற்கனவே உள்ள பொருளை சேர்',
      'no_products_available': 'பொருட்கள் எதுவும் இல்லை',
      'current': 'தற்போதைய',
      'price_on_sale': 'விற்பனை விலை',
      'added_to': 'சேர்க்கப்பட்டது',
    },
  };
}

