class PhoneCountryCodes {
  static const List<Map<String, String>> list = [
    // Priority (common for this app)
    {'code': '+91', 'flag': '🇮🇳', 'name': 'India'},
    {'code': '+1', 'flag': '🇺🇸', 'name': 'United States'},
    {'code': '+44', 'flag': '🇬🇧', 'name': 'United Kingdom'},
    {'code': '+971', 'flag': '🇦🇪', 'name': 'United Arab Emirates'},
    {'code': '+966', 'flag': '🇸🇦', 'name': 'Saudi Arabia'},
    {'code': '+974', 'flag': '🇶🇦', 'name': 'Qatar'},
    {'code': '+965', 'flag': '🇰🇼', 'name': 'Kuwait'},
    {'code': '+973', 'flag': '🇧🇭', 'name': 'Bahrain'},
    {'code': '+968', 'flag': '🇴🇲', 'name': 'Oman'},
    {'code': '+60', 'flag': '🇲🇾', 'name': 'Malaysia'},
    {'code': '+65', 'flag': '🇸🇬', 'name': 'Singapore'},

    // South Asia
    {'code': '+92', 'flag': '🇵🇰', 'name': 'Pakistan'},
    {'code': '+880', 'flag': '🇧🇩', 'name': 'Bangladesh'},
    {'code': '+94', 'flag': '🇱🇰', 'name': 'Sri Lanka'},
    {'code': '+977', 'flag': '🇳🇵', 'name': 'Nepal'},
    {'code': '+975', 'flag': '🇧🇹', 'name': 'Bhutan'},
    {'code': '+960', 'flag': '🇲🇻', 'name': 'Maldives'},
    {'code': '+93', 'flag': '🇦🇫', 'name': 'Afghanistan'},

    // East and Southeast Asia
    {'code': '+86', 'flag': '🇨🇳', 'name': 'China'},
    {'code': '+81', 'flag': '🇯🇵', 'name': 'Japan'},
    {'code': '+82', 'flag': '🇰🇷', 'name': 'South Korea'},
    {'code': '+852', 'flag': '🇭🇰', 'name': 'Hong Kong'},
    {'code': '+853', 'flag': '🇲🇴', 'name': 'Macau'},
    {'code': '+886', 'flag': '🇹🇼', 'name': 'Taiwan'},
    {'code': '+66', 'flag': '🇹🇭', 'name': 'Thailand'},
    {'code': '+84', 'flag': '🇻🇳', 'name': 'Vietnam'},
    {'code': '+62', 'flag': '🇮🇩', 'name': 'Indonesia'},
    {'code': '+63', 'flag': '🇵🇭', 'name': 'Philippines'},
    {'code': '+95', 'flag': '🇲🇲', 'name': 'Myanmar'},
    {'code': '+855', 'flag': '🇰🇭', 'name': 'Cambodia'},
    {'code': '+856', 'flag': '🇱🇦', 'name': 'Laos'},
    {'code': '+673', 'flag': '🇧🇳', 'name': 'Brunei'},
    {'code': '+670', 'flag': '🇹🇱', 'name': 'Timor-Leste'},
    {'code': '+976', 'flag': '🇲🇳', 'name': 'Mongolia'},

    // Central Asia and Caucasus
    {'code': '+7', 'flag': '🇷🇺', 'name': 'Russia'},
    {'code': '+7', 'flag': '🇰🇿', 'name': 'Kazakhstan'},
    {'code': '+996', 'flag': '🇰🇬', 'name': 'Kyrgyzstan'},
    {'code': '+998', 'flag': '🇺🇿', 'name': 'Uzbekistan'},
    {'code': '+992', 'flag': '🇹🇯', 'name': 'Tajikistan'},
    {'code': '+993', 'flag': '🇹🇲', 'name': 'Turkmenistan'},
    {'code': '+374', 'flag': '🇦🇲', 'name': 'Armenia'},
    {'code': '+994', 'flag': '🇦🇿', 'name': 'Azerbaijan'},
    {'code': '+995', 'flag': '🇬🇪', 'name': 'Georgia'},

    // Europe
    {'code': '+49', 'flag': '🇩🇪', 'name': 'Germany'},
    {'code': '+33', 'flag': '🇫🇷', 'name': 'France'},
    {'code': '+39', 'flag': '🇮🇹', 'name': 'Italy'},
    {'code': '+34', 'flag': '🇪🇸', 'name': 'Spain'},
    {'code': '+31', 'flag': '🇳🇱', 'name': 'Netherlands'},
    {'code': '+32', 'flag': '🇧🇪', 'name': 'Belgium'},
    {'code': '+41', 'flag': '🇨🇭', 'name': 'Switzerland'},
    {'code': '+43', 'flag': '🇦🇹', 'name': 'Austria'},
    {'code': '+45', 'flag': '🇩🇰', 'name': 'Denmark'},
    {'code': '+46', 'flag': '🇸🇪', 'name': 'Sweden'},
    {'code': '+47', 'flag': '🇳🇴', 'name': 'Norway'},
    {'code': '+48', 'flag': '🇵🇱', 'name': 'Poland'},
    {'code': '+351', 'flag': '🇵🇹', 'name': 'Portugal'},
    {'code': '+353', 'flag': '🇮🇪', 'name': 'Ireland'},
    {'code': '+354', 'flag': '🇮🇸', 'name': 'Iceland'},
    {'code': '+358', 'flag': '🇫🇮', 'name': 'Finland'},
    {'code': '+36', 'flag': '🇭🇺', 'name': 'Hungary'},
    {'code': '+420', 'flag': '🇨🇿', 'name': 'Czech Republic'},
    {'code': '+421', 'flag': '🇸🇰', 'name': 'Slovakia'},
    {'code': '+40', 'flag': '🇷🇴', 'name': 'Romania'},
    {'code': '+359', 'flag': '🇧🇬', 'name': 'Bulgaria'},
    {'code': '+30', 'flag': '🇬🇷', 'name': 'Greece'},
    {'code': '+385', 'flag': '🇭🇷', 'name': 'Croatia'},
    {'code': '+386', 'flag': '🇸🇮', 'name': 'Slovenia'},
    {'code': '+387', 'flag': '🇧🇦', 'name': 'Bosnia and Herzegovina'},
    {'code': '+381', 'flag': '🇷🇸', 'name': 'Serbia'},
    {'code': '+382', 'flag': '🇲🇪', 'name': 'Montenegro'},
    {'code': '+389', 'flag': '🇲🇰', 'name': 'North Macedonia'},
    {'code': '+355', 'flag': '🇦🇱', 'name': 'Albania'},
    {'code': '+373', 'flag': '🇲🇩', 'name': 'Moldova'},
    {'code': '+380', 'flag': '🇺🇦', 'name': 'Ukraine'},
    {'code': '+375', 'flag': '🇧🇾', 'name': 'Belarus'},
    {'code': '+423', 'flag': '🇱🇮', 'name': 'Liechtenstein'},
    {'code': '+356', 'flag': '🇲🇹', 'name': 'Malta'},
    {'code': '+357', 'flag': '🇨🇾', 'name': 'Cyprus'},
    {'code': '+377', 'flag': '🇲🇨', 'name': 'Monaco'},
    {'code': '+378', 'flag': '🇸🇲', 'name': 'San Marino'},

    // Middle East
    {'code': '+972', 'flag': '🇮🇱', 'name': 'Israel'},
    {'code': '+963', 'flag': '🇸🇾', 'name': 'Syria'},
    {'code': '+964', 'flag': '🇮🇶', 'name': 'Iraq'},
    {'code': '+98', 'flag': '🇮🇷', 'name': 'Iran'},
    {'code': '+90', 'flag': '🇹🇷', 'name': 'Turkey'},
    {'code': '+962', 'flag': '🇯🇴', 'name': 'Jordan'},
    {'code': '+961', 'flag': '🇱🇧', 'name': 'Lebanon'},
    {'code': '+970', 'flag': '🇵🇸', 'name': 'Palestine'},
    {'code': '+967', 'flag': '🇾🇪', 'name': 'Yemen'},

    // Africa
    {'code': '+20', 'flag': '🇪🇬', 'name': 'Egypt'},
    {'code': '+27', 'flag': '🇿🇦', 'name': 'South Africa'},
    {'code': '+234', 'flag': '🇳🇬', 'name': 'Nigeria'},
    {'code': '+254', 'flag': '🇰🇪', 'name': 'Kenya'},
    {'code': '+212', 'flag': '🇲🇦', 'name': 'Morocco'},
    {'code': '+213', 'flag': '🇩🇿', 'name': 'Algeria'},
    {'code': '+216', 'flag': '🇹🇳', 'name': 'Tunisia'},
    {'code': '+218', 'flag': '🇱🇾', 'name': 'Libya'},
    {'code': '+251', 'flag': '🇪🇹', 'name': 'Ethiopia'},
    {'code': '+255', 'flag': '🇹🇿', 'name': 'Tanzania'},
    {'code': '+256', 'flag': '🇺🇬', 'name': 'Uganda'},
    {'code': '+250', 'flag': '🇷🇼', 'name': 'Rwanda'},
    {'code': '+257', 'flag': '🇧🇮', 'name': 'Burundi'},
    {'code': '+233', 'flag': '🇬🇭', 'name': 'Ghana'},
    {'code': '+225', 'flag': '🇨🇮', 'name': 'Cote d\'Ivoire'},
    {'code': '+221', 'flag': '🇸🇳', 'name': 'Senegal'},
    {'code': '+237', 'flag': '🇨🇲', 'name': 'Cameroon'},
    {'code': '+243', 'flag': '🇨🇩', 'name': 'DR Congo'},
    {'code': '+242', 'flag': '🇨🇬', 'name': 'Congo'},
    {'code': '+244', 'flag': '🇦🇴', 'name': 'Angola'},
    {'code': '+258', 'flag': '🇲🇿', 'name': 'Mozambique'},
    {'code': '+263', 'flag': '🇿🇼', 'name': 'Zimbabwe'},
    {'code': '+260', 'flag': '🇿🇲', 'name': 'Zambia'},
    {'code': '+267', 'flag': '🇧🇼', 'name': 'Botswana'},
    {'code': '+264', 'flag': '🇳🇦', 'name': 'Namibia'},
    {'code': '+231', 'flag': '🇱🇷', 'name': 'Liberia'},
    {'code': '+232', 'flag': '🇸🇱', 'name': 'Sierra Leone'},
    {'code': '+220', 'flag': '🇬🇲', 'name': 'Gambia'},
    {'code': '+240', 'flag': '🇬🇶', 'name': 'Equatorial Guinea'},
    {'code': '+249', 'flag': '🇸🇩', 'name': 'Sudan'},
    {'code': '+211', 'flag': '🇸🇸', 'name': 'South Sudan'},

    // North America, Central America, Caribbean (+1 and others)
    {'code': '+1', 'flag': '🇨🇦', 'name': 'Canada'},
    {'code': '+52', 'flag': '🇲🇽', 'name': 'Mexico'},
    {'code': '+501', 'flag': '🇧🇿', 'name': 'Belize'},
    {'code': '+502', 'flag': '🇬🇹', 'name': 'Guatemala'},
    {'code': '+503', 'flag': '🇸🇻', 'name': 'El Salvador'},
    {'code': '+504', 'flag': '🇭🇳', 'name': 'Honduras'},
    {'code': '+505', 'flag': '🇳🇮', 'name': 'Nicaragua'},
    {'code': '+506', 'flag': '🇨🇷', 'name': 'Costa Rica'},
    {'code': '+507', 'flag': '🇵🇦', 'name': 'Panama'},
    {'code': '+53', 'flag': '🇨🇺', 'name': 'Cuba'},
    {'code': '+509', 'flag': '🇭🇹', 'name': 'Haiti'},
    {'code': '+1', 'flag': '🇯🇲', 'name': 'Jamaica'},
    {'code': '+1', 'flag': '🇹🇹', 'name': 'Trinidad and Tobago'},
    {'code': '+1', 'flag': '🇧🇸', 'name': 'Bahamas'},
    {'code': '+1', 'flag': '🇧🇧', 'name': 'Barbados'},
    {'code': '+1', 'flag': '🇬🇩', 'name': 'Grenada'},
    {'code': '+1', 'flag': '🇱🇨', 'name': 'Saint Lucia'},
    {'code': '+1', 'flag': '🇻🇨', 'name': 'Saint Vincent and the Grenadines'},
    {'code': '+1', 'flag': '🇦🇬', 'name': 'Antigua and Barbuda'},
    {'code': '+1', 'flag': '🇩🇲', 'name': 'Dominica'},
    {'code': '+1', 'flag': '🇰🇳', 'name': 'Saint Kitts and Nevis'},
    {'code': '+1', 'flag': '🇩🇴', 'name': 'Dominican Republic'},

    // South America
    {'code': '+55', 'flag': '🇧🇷', 'name': 'Brazil'},
    {'code': '+54', 'flag': '🇦🇷', 'name': 'Argentina'},
    {'code': '+56', 'flag': '🇨🇱', 'name': 'Chile'},
    {'code': '+57', 'flag': '🇨🇴', 'name': 'Colombia'},
    {'code': '+58', 'flag': '🇻🇪', 'name': 'Venezuela'},
    {'code': '+51', 'flag': '🇵🇪', 'name': 'Peru'},
    {'code': '+593', 'flag': '🇪🇨', 'name': 'Ecuador'},
    {'code': '+592', 'flag': '🇬🇾', 'name': 'Guyana'},
    {'code': '+597', 'flag': '🇸🇷', 'name': 'Suriname'},
    {'code': '+595', 'flag': '🇵🇾', 'name': 'Paraguay'},
    {'code': '+598', 'flag': '🇺🇾', 'name': 'Uruguay'},
    {'code': '+591', 'flag': '🇧🇴', 'name': 'Bolivia'},

    // Oceania
    {'code': '+61', 'flag': '🇦🇺', 'name': 'Australia'},
    {'code': '+64', 'flag': '🇳🇿', 'name': 'New Zealand'},
    {'code': '+679', 'flag': '🇫🇯', 'name': 'Fiji'},
    {'code': '+675', 'flag': '🇵🇬', 'name': 'Papua New Guinea'},
    {'code': '+677', 'flag': '🇸🇧', 'name': 'Solomon Islands'},
    {'code': '+678', 'flag': '🇻🇺', 'name': 'Vanuatu'},
    {'code': '+685', 'flag': '🇼🇸', 'name': 'Samoa'},
    {'code': '+676', 'flag': '🇹🇴', 'name': 'Tonga'},
    {'code': '+687', 'flag': '🇳🇨', 'name': 'New Caledonia'},
  ];
}

